const test=require('node:test');const assert=require('node:assert/strict');const {measure}=require('./metrics.cjs');
const member=(id,at='2026-01-01T00:00:00Z')=>({id,acceptedAt:at,source:'research'});
const order=(id,buyerId,sellerId,created,completed,other={})=>({id,buyerId,sellerId,createdAt:created,completedAt:completed,status:'completed',serverVerified:true,isTest:false,reversed:false,serviceAmountMicroFav:'100000000',...other});
function fixture(){return {source:'verified-server-export',asOf:'2026-03-01T00:00:00Z',members:[member('a'),member('b'),member('new','2026-02-25T00:00:00Z')],orders:[order('1','b','a','2026-01-02T00:00:00Z','2026-01-03T00:00:00Z'),order('2','a','b','2026-01-04T00:00:00Z','2026-01-05T00:00:00Z')],needs:[{id:'n1',memberId:'a',submittedAt:'2026-01-01T00:00:00Z',matchedAt:'2026-01-07T00:00:00Z'},{id:'n2',memberId:'new',submittedAt:'2026-02-27T00:00:00Z'}],assistance:[{at:'2026-01-03T00:00:00Z',minutes:20,orderId:'1'}]};}
test('30-day denominators exclude recent members and capture later participation',()=>{const out=measure(fixture());assert.deepEqual(out.activation30Days,{numerator:2,denominator:2,rate:1});assert.deepEqual(out.repeat30Days,{numerator:2,denominator:2,rate:1});assert.equal(out.earnThenSpendMembers,1);assert.equal(out.serviceVolumeFav,'200.000000');assert.equal(out.meanAssistanceMinutesPerCompletedOrder,10);});
test('seven-day match denominator excludes immature needs',()=>{assert.deepEqual(measure(fixture()).matchedWithin7Days,{numerator:1,denominator:1,rate:1});});
test('tests, reversals and incomplete orders do not inflate results',()=>{const f=fixture();f.orders.push({...f.orders[0],id:'test',isTest:true},{...f.orders[0],id:'reversed',reversed:true},{...f.orders[0],id:'funded',status:'funded'});assert.equal(measure(f).completedOrders,2);});
test('zero denominators return unknown rather than a fictitious zero rate',()=>{const f=fixture();f.members=[];f.orders=[];f.needs=[];f.assistance=[];const out=measure(f);assert.equal(out.activation30Days.rate,null);assert.equal(out.repeat30Days.rate,null);assert.equal(out.medianDaysToFirstCompletion,null);});
test('buy funded before sale completion is not an earn-then-spend loop',()=>{const f=fixture();f.orders[1].createdAt='2026-01-02T00:00:00Z';assert.equal(measure(f).earnThenSpendMembers,0);});
test('reject ambiguous time zones, duplicate IDs and unverified completions',()=>{const f=fixture();f.asOf='2026-03-01';assert.throws(()=>measure(f),/time zone/);const d=fixture();d.orders.push(d.orders[0]);assert.throws(()=>measure(d),/unique/);const u=fixture();u.orders[0].serverVerified=false;assert.throws(()=>measure(u),/verified/);});
test('large FAV integer amounts remain exact',()=>{const f=fixture();f.orders[0].serviceAmountMicroFav='9007199254740993';f.orders[1].serviceAmountMicroFav='1';assert.equal(measure(f).serviceVolumeMicroFav,'9007199254740994');});
test('unreviewed test or reversal flags cannot become marketing results',()=>{const f=fixture();f.orders[0].reversed=null;assert.throws(()=>measure(f),/flags/);});
test('campaign labels cannot collide with object prototypes',()=>{const f=fixture();f.members[0].source='__proto__';assert.equal(measure(f).bySource.__proto__.accepted,1);});
