import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { assignCommunityGroupModerator, removeCommunityGroupModerator, listCommunityGroups, getCommunityGroupMembers } from '../lib/social';
import './AdminPanel.css';

const ADMIN_EMAIL = 'adamzoharlevi@gmail.com';

export default function AdminPanel() {
  const [allowed, setAllowed] = useState(null); const [search, setSearch] = useState(''); const [users, setUsers] = useState([]); const [groups, setGroups] = useState([]); const [selectedGroup, setSelectedGroup] = useState(null); const [groupMembers, setGroupMembers] = useState([]); const [reports, setReports] = useState([]); const [loading, setLoading] = useState(true); const [workingId, setWorkingId] = useState(''); const [groupWorkingId, setGroupWorkingId] = useState(''); const [reportWorkingId, setReportWorkingId] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');

  async function checkAccess() { const { data: { user } } = await supabase.auth.getUser(); const isAllowed = Boolean(user?.email && user.email.toLowerCase() === ADMIN_EMAIL); if (!isAllowed) { setAllowed(false); setLoading(false); return false; } const { data, error: accessError } = await supabase.rpc('is_favourit_admin'); if (accessError) throw accessError; setAllowed(Boolean(data)); return Boolean(data); }
  async function loadUsers(term = search) { setError(''); try { const { data, error: rpcError } = await supabase.rpc('admin_list_users', { p_search: term.trim() }); if (rpcError) throw rpcError; setUsers(data || []); } catch (err) { setError(err.message || 'Could not load users.'); } }
  async function loadGroups() { try { const data = await listCommunityGroups(); setGroups(data || []); } catch (err) { setError(err.message || 'Could not load community groups.'); } }
  async function loadGroupMembers(groupId) { try { const data = await getCommunityGroupMembers(groupId); setGroupMembers(data || []); } catch (err) { setError(err.message || 'Could not load group members.'); } }
  async function loadReports() { try { const { data, error: rpcError } = await supabase.rpc('admin_list_community_reports'); if (rpcError) throw rpcError; setReports(data || []); } catch (err) { setError(err.message || 'Could not load community reports.'); } }
  useEffect(() => { let active = true; (async () => { try { const ok = await checkAccess(); if (active && ok) { await Promise.all([loadUsers(''), loadGroups(), loadReports()]); } } catch (err) { if (active) setError(err.message || 'Could not verify admin access.'); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  async function setMiddleman(user, enabled) { setWorkingId(user.user_id); setError(''); setNotice(''); try { const { error: actionError } = await supabase.rpc('admin_set_middleman_role', { p_user_id: user.user_id, p_enabled: enabled }); if (actionError) throw actionError; setNotice(enabled ? `${user.email || user.username || 'User'} is now a Middleman.` : `${user.email || user.username || 'User'} is no longer a Middleman.`); await loadUsers(); } catch (err) { setError(err.message || 'Could not change the role.'); } finally { setWorkingId(''); } }
  async function toggleGroupModerator(member) { if (!selectedGroup) return; setGroupWorkingId(member.user_id); setError(''); setNotice(''); try { if (member.is_moderator) await removeCommunityGroupModerator(selectedGroup.id, member.user_id); else await assignCommunityGroupModerator(selectedGroup.id, member.user_id); await loadGroupMembers(selectedGroup.id); setNotice(member.is_moderator ? `@${member.username || 'member'} is no longer a group moderator.` : `@${member.username || 'member'} is now a group moderator.`); } catch (err) { setError(err.message || 'Could not update group moderator.'); } finally { setGroupWorkingId(''); } }
  async function selectGroup(group) { setSelectedGroup(group); setGroupMembers([]); setError(''); await loadGroupMembers(group.id); }
  async function updateReport(report, status) { setReportWorkingId(report.report_id); setError(''); setNotice(''); try { const { error: rpcError } = await supabase.rpc('resolve_report', { p_report_id: report.report_id, p_status: status, p_note: `Community moderation status: ${status}.` }); if (rpcError) throw rpcError; setNotice(`Report marked ${status}.`); await loadReports(); } catch (err) { setError(err.message || 'Could not update report.'); } finally { setReportWorkingId(''); } }

  if (loading) return <div className="admin-shell"><div className="admin-loading">Checking admin access…</div></div>;
  if (!allowed) return <div className="admin-shell"><div className="admin-denied"><span>403</span><h1>Admin access only</h1><p>This area is restricted to the Favourit administrator.</p><a href="/">Return to Favourit</a></div></div>;

  return <main className="admin-shell">
    <header className="admin-header"><div><div className="eyebrow">FAVOURIT CONTROL CENTER</div><h1>Admin <span>Panel</span></h1><p>Manage trusted roles and keep the marketplace under control.</p></div><div className="admin-identity"><small>ADMIN</small><strong>{ADMIN_EMAIL}</strong></div></header>

    <section className="admin-card admin-users-card"><div className="admin-card-heading"><div><h2>User management</h2><p>Search a user and give or remove Middleman access.</p></div><div className="admin-role-pill">● Middleman</div></div><form className="admin-search" onSubmit={e => { e.preventDefault(); loadUsers(); }}><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search email, username or name…"/><button className="primary" type="submit">Search</button></form>{notice && <div className="admin-notice">✓ {notice}</div>}{error && <div className="admin-error">{error}</div>}<div className="admin-table"><div className="admin-row admin-row-head"><span>User</span><span>Role</span><span>Joined</span><span>Action</span></div>{users.map(user => <div className="admin-row" key={user.user_id}><div className="admin-user"><div className="admin-avatar">{(user.display_name || user.username || user.email || 'U').slice(0,1).toUpperCase()}</div><div><strong>{user.display_name || user.username || 'Unnamed user'}</strong><small>{user.email || 'No email'}</small></div></div><span className={`admin-role ${user.role}`}>{user.role}</span><span className="admin-date">{user.created_at ? new Date(user.created_at).toLocaleDateString() : '—'}</span><div>{user.role === 'middleman' ? <button className="danger-button" disabled={workingId === user.user_id} onClick={() => setMiddleman(user, false)}>{workingId === user.user_id ? 'Saving…' : 'Remove'}</button> : user.role === 'admin' ? <span className="protected-role">Protected</span> : <button className="secondary" disabled={workingId === user.user_id} onClick={() => setMiddleman(user, true)}>{workingId === user.user_id ? 'Saving…' : 'Make Middleman'}</button>}</div></div>)}{!users.length && <div className="admin-empty">No users found.</div>}</div></section>

    <section className="admin-card community-admin-card"><div className="admin-card-heading"><div><h2>Community moderation</h2><p>Assign group moderators. Moderators can remove messages and members from their assigned community.</p></div><div className="admin-role-pill">● Community</div></div><div className="community-admin-layout"><div className="community-admin-groups">{groups.map(group => <button key={group.id} className={`community-admin-group ${selectedGroup?.id === group.id ? 'selected' : ''}`} onClick={() => selectGroup(group)}><span>{group.name}</span><small>{Number(group.member_count || 0).toLocaleString()} members</small></button>)}{!groups.length && <div className="admin-empty">No public groups found.</div>}</div><div className="community-admin-members">{selectedGroup ? <><div className="admin-subheading"><strong>{selectedGroup.name}</strong><span>{groupMembers.length} members</span></div>{groupMembers.map(member => <div className="community-admin-member" key={member.user_id}><div className="admin-user"><div className="admin-avatar">{(member.display_name || member.username || 'U').slice(0,1).toUpperCase()}</div><div><strong>{member.display_name || 'Unnamed user'}</strong><small>@{member.username || 'member'}</small></div></div>{member.is_moderator ? <button className="danger-button" disabled={groupWorkingId === member.user_id} onClick={() => toggleGroupModerator(member)}>{groupWorkingId === member.user_id ? 'Saving…' : 'Remove moderator'}</button> : <button className="secondary" disabled={groupWorkingId === member.user_id} onClick={() => toggleGroupModerator(member)}>{groupWorkingId === member.user_id ? 'Saving…' : 'Make moderator'}</button>}</div>)}{!groupMembers.length && <div className="admin-empty">This group has no members yet.</div>}</> : <div className="admin-empty">Select a community to manage its moderators.</div>}</div></div></section>

    <section className="admin-card community-reports-card"><div className="admin-card-heading"><div><h2>Community reports</h2><p>Reports are retained with the original message, including messages that were deleted by their author.</p></div><div className="admin-role-pill">● Reports · {reports.length}</div></div>{reports.length ? <div className="community-report-list">{reports.map(report => <article className="community-report-row" key={report.report_id}><div className="community-report-meta"><strong>{report.reason}</strong><span>{report.group_name} · {new Date(report.created_at).toLocaleString()}</span><small>Reported by @{report.reporter_username || 'member'} · Message by @{report.message_username || 'member'}</small></div><div className="community-report-message"><p>{report.message_body}</p>{report.message_deleted_at && <span className="community-report-deleted">Deleted in chat — retained for moderation</span>}<small>{report.details || 'No additional details.'}</small></div><div className="community-report-actions"><span className={`admin-role ${report.status}`}>{report.status}</span><button className="secondary" disabled={reportWorkingId === report.report_id} onClick={() => updateReport(report, 'reviewing')}>Review</button><button className="primary" disabled={reportWorkingId === report.report_id} onClick={() => updateReport(report, 'resolved')}>Resolve</button><button className="danger-button" disabled={reportWorkingId === report.report_id} onClick={() => updateReport(report, 'dismissed')}>Dismiss</button></div></article>)}</div> : <div className="admin-empty">No community reports yet.</div>}</section>

    <section className="admin-grid"><div className="admin-card admin-info"><span className="admin-icon">◈</span><h3>Middleman permissions</h3><p>Middlemen can mediate assigned orders, read the buyer–seller conversation, view escrow and resolve disputes.</p></div><div className="admin-card admin-info"><span className="admin-icon">✓</span><h3>Community safety</h3><p>Group messages are reportable, moderators can remove harmful content, and posting is rate-limited to reduce spam.</p></div></section>
  </main>;
}
