import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import './AdminMessageReports.css';

export default function AdminMessageReports(){
 const [reports,setReports]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const {data,error:e}=await supabase.rpc('admin_list_message_reports');if(e)throw e;setReports(data||[]);}catch(e){setError(e.message||'Could not load reports.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const resolve=async(report,status)=>{try{const {error:e}=await supabase.rpc('resolve_report',{p_report_id:report.id,p_status:status,p_note:''});if(e)throw e;await load();}catch(e){setError(e.message||'Could not update report.');}};
 return <section className="admin-message-reports admin-card"><div className="admin-card-heading"><div><h2>Message reports</h2><p>Direct and community reports stay in the database, including deleted message content.</p></div><button className="secondary" onClick={load}>Refresh</button></div>{error&&<div className="admin-error">{error}</div>}{loading?<div className="admin-empty">Loading reports…</div>:!reports.length?<div className="admin-empty">No message reports yet.</div>:<div className="admin-report-list">{reports.map(r=><article className="admin-report" key={r.id}><div className="admin-report-top"><div><strong>{r.target_type==='community_group_message'?'Community message':'Direct message'}</strong><small>{new Date(r.created_at).toLocaleString()} · reported by @{r.reporter_username||'member'}</small></div><span className={`report-status ${r.status}`}>{r.status}</span></div><div className="admin-report-context"><small>{r.community_name?`Community: ${r.community_name}`:`Sender: @${r.message_sender_username||'member'}`}</small><p>{r.message_body||'Message unavailable.'}</p></div><div className="admin-report-reason"><b>{r.reason}</b>{r.details&&<span>{r.details}</span>}</div><div className="admin-report-actions">{r.status==='open'&&<><button className="secondary" onClick={()=>resolve(r,'reviewing')}>Review</button><button className="secondary" onClick={()=>resolve(r,'dismissed')}>Dismiss</button><button className="primary" onClick={()=>resolve(r,'resolved')}>Resolve</button></>}{r.status==='reviewing'&&<><button className="secondary" onClick={()=>resolve(r,'dismissed')}>Dismiss</button><button className="primary" onClick={()=>resolve(r,'resolved')}>Resolve</button></>}{r.is_deleted&&<span className="report-deleted">Deleted / retained</span>}</div></article>)}</div>}</section>;
}
