import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';
import { getDirectMessages, getMyDirectConversations, getOrCreateDirectConversation, searchUsersByUsername, sendDirectMessage, deleteOwnDirectMessage, toggleDirectMessageStar, reportDirectMessage } from '../lib/directMessaging';
import { getMySocialGraph, listCommunityGroups, getCommunityGroupMessages, sendCommunityGroupMessage, deleteOwnCommunityGroupMessage, toggleCommunityGroupMessageStar, reportCommunityGroupMessage } from '../lib/social';
import './DirectMessaging.css';

const TYPING_TTL_MS=5000;
const REPORT_CATEGORIES=['Harassment or bullying','Spam or scam','Hate or discrimination','Sexual content','Violence or threats','Impersonation','Illegal activity','Other'];
const GROUP_ICONS={designers:'✦',developers:'⌘','video-editors':'▣',musicians:'♫',marketers:'↗',photographers:'◉',writers:'✎',entrepreneurs:'◇'};
const initials=name=>String(name||'Favourit member').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'FV';
const formatTime=value=>value?new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'';
const preferredLanguage=()=>{try{return localStorage.getItem('favourit_language')||localStorage.getItem('favourit:language')||navigator.language||'en';}catch(_){return 'en';}};

async function translateText(text,target){const lang=String(target||'en').split('-')[0].toLowerCase();if(!text||(!lang)||lang==='en'&&/^[\x00-\x7F]*$/.test(text))return text;const response=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=auto|${encodeURIComponent(lang)}`);if(!response.ok)throw new Error('Translation service is unavailable.');const data=await response.json();return data?.responseData?.translatedText||text;}
function Avatar({person,large=false}){const name=person?.display_name||person?.username;return person?.avatar_url?<img className={`dm-avatar ${large?'large':''}`} src={person.avatar_url} alt=""/>:<span className={`dm-avatar ${large?'large':''}`}>{initials(name)}</span>}
function openProfile(person){const userId=person?.user_id||person?.id;if(!userId&&!person?.username)return;window.dispatchEvent(new CustomEvent('favourit:open-profile',{detail:{userId,username:person?.username}}));}

export default function DirectMessaging({session}){
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState([]),[conversations,setConversations]=useState([]),[communities,setCommunities]=useState([]),[section,setSection]=useState('people'),[selected,setSelected]=useState(null),[selectedType,setSelectedType]=useState('direct'),[conversationId,setConversationId]=useState(null),[messages,setMessages]=useState([]),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[otherReadAt,setOtherReadAt]=useState(null),[typingByConversation,setTypingByConversation]=useState({}),[menuId,setMenuId]=useState(null),[replyTo,setReplyTo]=useState(null),[forwardItem,setForwardItem]=useState(null),[reportItem,setReportItem]=useState(null),[reportCategory,setReportCategory]=useState(REPORT_CATEGORIES[0]),[reportDetails,setReportDetails]=useState(''),[translation,setTranslation]=useState(null),[translationBusy,setTranslationBusy]=useState(false),[friendRequestCount,setFriendRequestCount]=useState(0);
  const audioRef=useRef(null),endRef=useRef(null),bodyRef=useRef(''),conversationIdRef=useRef(null),typingChannelsRef=useRef(new Map()),typingLastSeenRef=useRef(new Map()),typingLastEventRef=useRef(new Map()),ownTypingAtRef=useRef(new Map());
  useEffect(()=>{conversationIdRef.current=conversationId;},[conversationId]);
  const setRemoteTyping=(id,timestamp)=>{const incoming=Number(timestamp)||Date.now(),previous=typingLastEventRef.current.get(id)||0;if(incoming<previous)return;typingLastEventRef.current.set(id,incoming);typingLastSeenRef.current.set(id,incoming);setTypingByConversation(v=>v[id]?v:{...v,[id]:true});};
  const expireTyping=id=>{const last=typingLastSeenRef.current.get(id);if(!last||Date.now()-last<TYPING_TTL_MS)return;typingLastSeenRef.current.delete(id);setTypingByConversation(v=>{if(!v[id])return v;const n={...v};delete n[id];return n;});};
  const ensureTypingChannel=id=>{if(!id||!supabase||!session?.user?.id)return Promise.resolve(null);const existing=typingChannelsRef.current.get(id);if(existing)return existing.readyPromise;const channel=supabase.channel(`direct-typing-${id}`,{config:{broadcast:{self:false}}});let resolveReady;const readyPromise=new Promise(resolve=>{resolveReady=resolve;});const entry={channel,subscribed:false,readyPromise};typingChannelsRef.current.set(id,entry);channel.on('broadcast',{event:'typing'},event=>{const data=event?.payload||{};if(data.user_id===session.user.id||data.conversation_id!==id)return;setRemoteTyping(id,data.typing_at);}).subscribe(status=>{const current=typingChannelsRef.current.get(id);if(!current||current.channel!==channel)return;if(status==='SUBSCRIBED'){current.subscribed=true;resolveReady(channel);}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){typingChannelsRef.current.delete(id);try{supabase.removeChannel(channel);}catch(_){}resolveReady(null);}});return readyPromise;};
  const sendTyping=id=>{const entry=typingChannelsRef.current.get(id);if(!entry?.subscribed||!session?.user?.id)return;entry.channel.send({type:'broadcast',event:'typing',payload:{conversation_id:id,user_id:session.user.id,typing_at:Date.now()}}).catch(()=>{});};
  const announceTyping=id=>{if(!id||!bodyRef.current.trim())return;ownTypingAtRef.current.set(id,Date.now());ensureTypingChannel(id).then(ch=>{if(ch&&ownTypingAtRef.current.has(id))sendTyping(id);}).catch(()=>{});};
  const refreshPeople=async()=>{try{setConversations(await getMyDirectConversations());}catch(e){setError(e.message||'Could not load conversations.');}};
  const refreshCommunities=async()=>{try{const data=await listCommunityGroups();setCommunities((data||[]).filter(g=>g.is_joined));}catch(e){setError(e.message||'Could not load communities.');}};
  const refreshRequests=async()=>{try{const g=await getMySocialGraph();setFriendRequestCount(Array.isArray(g?.incoming)?g.incoming.length:0);}catch(_){}};
  const refreshAll=async()=>{await Promise.all([refreshPeople(),refreshCommunities(),refreshRequests()]);};
  useEffect(()=>{if(session?.user?.id)refreshAll();},[session?.user?.id]);
  useEffect(()=>{if(!open||!query.trim()){setResults([]);return;}const timer=setTimeout(()=>searchUsersByUsername(query).then(setResults).catch(e=>setError(e.message||'Search failed.')),220);return()=>clearTimeout(timer);},[open,query]);
  useEffect(()=>{if(!session?.user?.id)return;const ids=conversations.map(c=>c.conversation_id).filter(Boolean);ids.forEach(id=>ensureTypingChannel(id));const timer=setInterval(()=>typingLastSeenRef.current.forEach((_,id)=>expireTyping(id)),250);return()=>clearInterval(timer);},[conversations,session?.user?.id]);
  useEffect(()=>{if(!open||!supabase||!session?.user?.id)return;const channel=supabase.channel(`direct-inbox-${session.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},payload=>{if(payload.new.sender_id!==session.user.id)refreshPeople();}).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications'},payload=>{if(payload.new.user_id===session.user.id&&payload.new.type==='friend_request'){refreshRequests();window.dispatchEvent(new CustomEvent('favourit:friend-request-updated'));}}).subscribe();const timer=setInterval(refreshPeople,8000);return()=>{clearInterval(timer);try{supabase.removeChannel(channel);}catch(_){}};},[open,session?.user?.id]);
  useEffect(()=>{if(!open)return;const close=()=>setMenuId(null);document.addEventListener('click',close);return()=>document.removeEventListener('click',close);},[open]);
  useEffect(()=>{bodyRef.current=body;},[body]);useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'});},[messages,typingByConversation]);
  const markRead=async id=>{try{await supabase.rpc('mark_conversation_read',{p_conversation_id:id});}catch(_){}};
  const refreshRead=async id=>{try{const {data,error:e}=await supabase.rpc('get_conversation_read_state',{p_conversation_id:id});if(!e)setOtherReadAt(data?.[0]?.other_last_read_at||null);}catch(_){}};
  const loadDirect=async id=>{const data=await getDirectMessages(id);setMessages(data);await markRead(id);await refreshRead(id);await ensureTypingChannel(id);};
  const loadCommunity=async id=>setMessages(await getCommunityGroupMessages(id));
  useEffect(()=>{if(!selected||!conversationId)return;let active=true;const load=async()=>{try{if(selectedType==='direct')await loadDirect(conversationId);else await loadCommunity(conversationId);}catch(e){if(active)setError(e.message||'Could not load messages.');}};load();const timer=setInterval(()=>{if(selectedType==='direct'){loadDirect(conversationId).catch(()=>{});}else loadCommunity(conversationId).catch(()=>{});},selectedType==='direct'?2000:2500);return()=>{active=false;clearInterval(timer);};},[conversationId,selectedType]);
  const openMessenger=()=>{setOpen(true);setError('');refreshAll();if(!audioRef.current){try{const C=window.AudioContext||window.webkitAudioContext;audioRef.current=C?new C():null;}catch(_){}}};
  const openDirect=async user=>{if(!user?.username||busy)return;setBusy(true);setError('');try{const id=await getOrCreateDirectConversation(user.username);await ensureTypingChannel(id);setSelected(user);setSelectedType('direct');setConversationId(id);setSection('people');setQuery('');setResults([]);setOpen(true);}catch(e){setError(e.message||'Could not open conversation.');}finally{setBusy(false);}};
  const openExisting=(c)=>{setSelected({user_id:c.other_user_id,username:c.other_username,display_name:c.other_display_name,avatar_url:c.other_avatar_url,is_friend:c.is_friend,is_online:c.is_online,last_seen_at:c.last_seen_at});setSelectedType('direct');setConversationId(c.conversation_id);setSection('people');setMenuId(null);};
  const openCommunity=(g)=>{setSelected(g);setSelectedType('community');setConversationId(g.id);setSection('communities');setMenuId(null);};
  useEffect(()=>{const handler=e=>{if(e.detail?.username)openDirect({username:e.detail.username});};window.addEventListener('favourit:open-direct-message',handler);return()=>window.removeEventListener('favourit:open-direct-message',handler);},[busy]);
  const leave=async()=>{if(selectedType==='direct')await markRead(conversationId);setSelected(null);setSelectedType('direct');setConversationId(null);setMessages([]);setBody('');setReplyTo(null);setOpen(true);refreshAll();};
  const close=async()=>{if(conversationId&&selectedType==='direct')await markRead(conversationId);setOpen(false);setSelected(null);setConversationId(null);setMessages([]);setBody('');setReplyTo(null);};
  const send=async e=>{e.preventDefault();if(!body.trim()||!conversationId||busy)return;setBusy(true);setError('');try{if(selectedType==='direct'){const msg=await sendDirectMessage(conversationId,body.trim(),replyTo?.id||null);setMessages(v=>v.some(x=>x.id===msg.id)?v:[...v,{...msg,username:session.user.user_metadata?.username,display_name:session.user.user_metadata?.display_name,sender_id:session.user.id}]);}else await sendCommunityGroupMessage(conversationId,body.trim(),replyTo?.id||null);setBody('');bodyRef.current='';ownTypingAtRef.current.delete(conversationId);setReplyTo(null);refreshAll();}catch(e){setError(e.message||'Could not send message.');}finally{setBusy(false);}};
  const handleBody=e=>{const value=e.target.value;setBody(value);bodyRef.current=value;if(value.trim())announceTyping(conversationId);else ownTypingAtRef.current.delete(conversationId);};
  const removeMessage=async item=>{setBusy(true);setError('');try{if(selectedType==='direct')await deleteOwnDirectMessage(item.id);else await deleteOwnCommunityGroupMessage(item.id);setMessages(selectedType==='direct'?await getDirectMessages(conversationId):await getCommunityGroupMessages(conversationId));}catch(e){setError(e.message||'Could not delete message.');}finally{setBusy(false);setMenuId(null);}};
  const starMessage=async item=>{setBusy(true);try{if(selectedType==='direct')await toggleDirectMessageStar(item.id);else await toggleCommunityGroupMessageStar(item.id);setMessages(selectedType==='direct'?await getDirectMessages(conversationId):await getCommunityGroupMessages(conversationId));}catch(e){setError(e.message||'Could not update star.');}finally{setBusy(false);setMenuId(null);}};
  const copy=async item=>{if(item.is_deleted)return;try{await navigator.clipboard.writeText(item.body);}catch(_){setError('Could not copy the message.');}setMenuId(null);};
  const report=async()=>{if(!reportItem)return;setBusy(true);try{if(selectedType==='direct')await reportDirectMessage(reportItem.id,reportCategory,reportDetails);else await reportCommunityGroupMessage(reportItem.id,reportCategory,reportDetails);setReportItem(null);setReportDetails('');setReportCategory(REPORT_CATEGORIES[0]);}catch(e){setError(e.message||'Could not submit report.');}finally{setBusy(false);}};
  const forward=async target=>{if(!forwardItem)return;setBusy(true);try{if(target.type==='direct')await sendDirectMessage(target.id,forwardItem.body);else await sendCommunityGroupMessage(target.id,forwardItem.body);setForwardItem(null);setMenuId(null);}catch(e){setError(e.message||'Could not forward message.');}finally{setBusy(false);}};
  const translate=async item=>{if(item.is_deleted)return;setTranslationBusy(true);setMenuId(null);try{setTranslation({item,text:await translateText(item.body,preferredLanguage())});}catch(e){setError(e.message||'Could not translate message.');}finally{setTranslationBusy(false);}};
  const unread=conversations.reduce((n,c)=>n+(c.conversation_id===conversationId&&open?0:Number(c.unread_count||0)),0);
  const friendOnline=Boolean(selectedType==='direct'&&selected?.is_friend&&selected?.is_online);
  const status=friendOnline?'Online':selectedType==='direct'&&selected?.is_friend&&selected?.last_seen_at?`Last seen ${new Date(selected.last_seen_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}`:'';
  const lastMine=[...messages].reverse().find(m=>m.sender_id===session.user.id),read=Boolean(lastMine?.created_at&&otherReadAt&&new Date(otherReadAt)>=new Date(lastMine.created_at));
  const conversationMeta=selectedType==='direct'?(friendOnline?'Online':status||((typingByConversation[conversationId])?'typing…':read?'Read':lastMine?'Sent':'')):`${selected?.member_count||''} members`;
  const filteredPeople=useMemo(()=>conversations,[conversations]);
  const forwardTargets=useMemo(()=>[...conversations.map(c=>({type:'direct',id:c.conversation_id,label:c.other_display_name||`@${c.other_username}`,username:c.other_username,avatar_url:c.other_avatar_url})),...communities.map(g=>({type:'community',id:g.id,label:g.name,username:'Community',icon:GROUP_ICONS[g.slug]||'◇'}))],[conversations,communities]);
  if(!session)return null;
  return <>
    <button className="dm-fab" onClick={openMessenger} aria-label="Messages"><span className="dm-fab-icon">⌁</span><span>Messages</span>{unread>0&&<b className="dm-unread-dot">{unread>9?'9+':unread}</b>}{friendRequestCount>0&&<i className="dm-request-dot">{friendRequestCount>9?'9+':friendRequestCount}</i>}</button>
    {open&&<div className="dm-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className={`dm-panel ${selected?'is-thread':'is-inbox'}`}>
      {!selected?<><header className="dm-header"><div><div className="eyebrow">MESSAGES</div><h2>Messages</h2><p>People, groups and communities in one place.</p></div><button className="dm-close" onClick={close}>×</button></header>
        <div className="dm-sections"><button className={section==='people'?'active':''} onClick={()=>setSection('people')}>People{unread>0&&<span>{unread}</span>}</button><button className={section==='groups'?'active':''} onClick={()=>setSection('groups')}>Groups</button><button className={section==='communities'?'active':''} onClick={()=>setSection('communities')}>Communities{communities.length>0&&<span>{communities.length}</span>}</button></div>
        <div className="dm-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people by @username…"/></div>
        {query.trim()&&<div className="dm-search-results">{results.map(person=><button key={person.id||person.user_id||person.username} onClick={()=>openDirect(person)}><Avatar person={person}/><span><strong>{person.display_name||person.username}</strong><small>@{person.username}</small></span></button>)}{!results.length&&<div className="dm-empty">No people found.</div>}</div>}
        {!query.trim()&&section==='people'&&<div className="dm-list">{filteredPeople.map(c=><button className="dm-list-row" key={c.conversation_id} onClick={()=>openExisting(c)}><Avatar person={{avatar_url:c.other_avatar_url,display_name:c.other_display_name,username:c.other_username}}/><span className="dm-list-copy"><strong>{c.other_display_name||`@${c.other_username}`} {c.is_friend&&c.is_online&&<i className="online-dot"/>}</strong><small>@{c.other_username} · {c.last_message||'Start a conversation'}</small></span><span className="dm-list-meta">{c.is_friend?(c.is_online?'Online':c.last_seen_at?`Seen ${new Date(c.last_seen_at).toLocaleDateString()}`:'') : formatTime(c.last_message_at)}{c.unread_count>0&&<b>{c.unread_count}</b>}</span></button>)}{!filteredPeople.length&&<div className="dm-empty"><h3>No personal chats yet.</h3><p>Search for a @username above to start one.</p></div>}</div>}
        {!query.trim()&&section==='groups'&&<div className="dm-empty"><h3>No group chats yet.</h3><p>Group conversations can live here separately from skill communities.</p></div>}
        {!query.trim()&&section==='communities'&&<div className="dm-list">{communities.map(g=><button className="dm-list-row" key={g.id} onClick={()=>openCommunity(g)}><span className="dm-community-icon">{GROUP_ICONS[g.slug]||'◇'}</span><span className="dm-list-copy"><strong>{g.name}</strong><small>Community chat · {Number(g.member_count||0).toLocaleString()} members</small></span><span className="dm-list-meta">Joined</span></button>)}{!communities.length&&<div className="dm-empty"><h3>No communities yet.</h3><p>Join a skill community and its chat will appear here.</p></div>}</div>}
      </>:<><header className="dm-thread-header"><button className="dm-back" onClick={leave}>←</button><button className="dm-thread-identity" onClick={()=>selectedType==='direct'&&openProfile(selected)}><Avatar person={selected} large/><span><strong>{selectedType==='community'?selected.name:(selected.display_name||`@${selected.username}`)}</strong>{selectedType==='direct'&&<small>@{selected.username}</small>}<em>{conversationMeta}</em></span>{selectedType==='direct'&&selected?.is_friend&&<i className={`thread-online ${friendOnline?'on':''}`}/>}</button><button className="dm-close" onClick={close}>×</button></header>
        {error&&<div className="dm-error">{error}</div>}
        <div className="dm-messages">{messages.map(item=>{const mine=item.sender_id===session.user.id;const deleted=Boolean(item.is_deleted);return <article className={`dm-message-row ${mine?'mine':''} ${deleted?'deleted':''}`} key={item.id}><Avatar person={item}/><div className="dm-message-wrap"><div className="dm-message-head"><button onClick={()=>openProfile(item)}>{item.display_name||item.username||'Member'}</button><time>{formatTime(item.created_at)}</time>{item.is_starred&&<span className="star-mark">★</span>}</div>{item.reply_to_message_id&&<div className="dm-reply-preview">↩ {item.reply_to_username?`@${item.reply_to_username}`:''}: {item.reply_to_body||'Message deleted.'}</div>}<div className="dm-message-line"><p>{deleted?(item.deleted_by_self?'You deleted a message.':item.body):item.body}</p><button className="dm-more" type="button" onClick={e=>{e.stopPropagation();setMenuId(menuId===item.id?null:item.id);}}>•••</button>{menuId===item.id&&<div className="dm-message-menu" onClick={e=>e.stopPropagation()}><button onClick={()=>{setReplyTo(item);setMenuId(null);}}>↩ Reply</button><button onClick={()=>{setForwardItem(item);setMenuId(null);}}>➜ Forward</button><button disabled={deleted} onClick={()=>copy(item)}>⧉ Copy</button><button disabled={deleted} onClick={()=>starMessage(item)}>{item.is_starred?'★ Unstar':'☆ Star'}</button>{mine&&selectedType==='direct'&&<button disabled={deleted} onClick={()=>removeMessage(item)}>⌫ Delete</button>}{mine&&selectedType==='community'&&<button disabled={deleted} onClick={()=>removeMessage(item)}>⌫ Delete</button>}{!mine&&<button disabled={deleted} onClick={()=>translate(item)}>文 Translate</button>}{!mine&&<button disabled={deleted} onClick={()=>{setReportItem(item);setMenuId(null);}}>⚑ Report</button>}</div>}</div></div></article>;})}{typingByConversation[conversationId]&&selectedType==='direct'&&<div className="dm-typing"><span/><span/><span/> typing…</div>}<div ref={endRef}/></div>
        {replyTo&&<div className="dm-reply-bar"><span>Replying to <strong>{replyTo.display_name||replyTo.username||'member'}</strong><small>{replyTo.body}</small></span><button onClick={()=>setReplyTo(null)}>×</button></div>}
        <form className="dm-composer" onSubmit={send}><input value={body} onChange={handleBody} placeholder={selectedType==='community'?'Message this community…':'Write a message…'} disabled={busy}/><button className="primary" disabled={busy||!body.trim()}>{busy?'…':'Send'}</button></form>
      </>}
      {forwardItem&&<div className="dm-modal-backdrop"><div className="dm-modal"><header><div><div className="eyebrow">FORWARD</div><h3>Send message to…</h3></div><button onClick={()=>setForwardItem(null)}>×</button></header><div className="dm-forward-preview">{forwardItem.body}</div><div className="dm-forward-list">{forwardTargets.map(target=><button key={`${target.type}-${target.id}`} onClick={()=>forward(target)}><Avatar person={target}/><span><strong>{target.label}</strong><small>{target.type==='community'?'Community':'Personal chat'}</small></span></button>)}</div></div></div>}
      {reportItem&&<div className="dm-modal-backdrop"><div className="dm-modal"><header><div><div className="eyebrow">REPORT MESSAGE</div><h3>Why are you reporting this?</h3></div><button onClick={()=>setReportItem(null)}>×</button></header><select value={reportCategory} onChange={e=>setReportCategory(e.target.value)}>{REPORT_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value)} maxLength={2000} placeholder="Tell us what happened…"/><div className="dm-modal-actions"><button className="secondary" onClick={()=>setReportItem(null)}>Cancel</button><button className="primary" disabled={busy} onClick={report}>{busy?'Sending…':'Submit report'}</button></div></div></div>}
      {translation&&<div className="dm-modal-backdrop"><div className="dm-modal"><header><div><div className="eyebrow">TRANSLATION</div><h3>Translated message</h3></div><button onClick={()=>setTranslation(null)}>×</button></header><p className="dm-translation-original">{translation.item.body}</p><p className="dm-translation-result">{translation.text}</p></div></div>}
      {translationBusy&&<div className="dm-translation-loading">Translating…</div>}
      </section></div>}
  </>;
}
