import { useEffect, useRef, useState } from 'react';
import { getDirectMessages, getOrCreateDirectConversation, searchUsersByUsername, sendDirectMessage } from '../lib/directMessaging';
import './DirectMessaging.css';

export default function DirectMessaging({ session }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [selected, setSelected] = useState(null); const [conversationId, setConversationId] = useState(null); const [messages, setMessages] = useState([]); const [body, setBody] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const endRef = useRef(null);
  useEffect(()=>{ if(!open || !query.trim()){setResults([]);return;} const timer=setTimeout(()=>searchUsersByUsername(query).then(setResults).catch(e=>setError(e.message||'Search failed.')),250); return()=>clearTimeout(timer); },[open,query]);
  useEffect(()=>{ if(!conversationId)return; let active=true; const load=async()=>{try{const data=await getDirectMessages(conversationId);if(active)setMessages(data);}catch(e){if(active)setError(e.message||'Could not load messages.')}}; load(); const channel=supabaseChannel(conversationId,()=>load()); return()=>{active=false;channel?.unsubscribe?.();}; },[conversationId]);
  useEffect(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),[messages]);
  const start=async user=>{setBusy(true);setError('');try{const id=await getOrCreateDirectConversation(user.username);setSelected(user);setConversationId(id);setQuery('');setResults([]);}catch(e){setError(e.message||'Could not open conversation.')}finally{setBusy(false)}};
  const send=async e=>{e.preventDefault();if(!body.trim()||!conversationId||busy)return;setBusy(true);try{const msg=await sendDirectMessage(conversationId,body);setMessages(v=>[...v,msg]);setBody('');}catch(e){setError(e.message||'Could not send message.')}finally{setBusy(false)}};
  if(!session)return null;
  return <><button className="dm-fab" onClick={()=>setOpen(true)} aria-label="Messages">✉<span>Messages</span></button>{open&&<div className="dm-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="dm-panel"><header><div><div className="eyebrow">FAVOURIT MESSAGES</div><h2>{selected?`@${selected.username}`:'Message someone'}</h2></div><button className="dm-close" onClick={()=>setOpen(false)}>×</button></header>{error&&<div className="dm-error">{error}</div>}{!selected?<><div className="dm-search"><span>@</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Type a @username…"/></div><div className="dm-results">{results.map(user=><button key={user.user_id} onClick={()=>start(user)} disabled={busy}><div className="dm-avatar">{(user.display_name||user.username).slice(0,1).toUpperCase()}</div><div><strong>{user.display_name}</strong><span>@{user.username}</span></div><b>→</b></button>)}{query.trim()&&!results.length&&<p className="dm-empty">No Favourit member found for @{query.replace(/^@/,'')}.</p>}</div><div className="dm-tip">Search anyone by their @ and start a private conversation.</div></>:<><div className="dm-thread">{messages.length?messages.map(m=><div className={m.sender_id===session.user.id?'dm-message mine':'dm-message'} key={m.id}><span>{m.body}</span><small>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>):<div className="dm-empty">Say hello to @{selected.username} 👋</div>}<div ref={endRef}/></div><form className="dm-compose" onSubmit={send}><input value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} placeholder={`Message @${selected.username}…`} autoFocus/><button className="primary" disabled={busy||!body.trim()}>Send</button></form><button className="dm-new" onClick={()=>setSelected(null)}>← Message someone else</button></>}</section></div>}</>;
}

function supabaseChannel(conversationId, onChange){
  // Realtime is optional here; the next refresh still works without it.
  try { const { supabase } = require('../lib/supabase'); const channel=supabase.channel(`direct-${conversationId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${conversationId}`},onChange).subscribe(); return channel; } catch (_) { return null; }
}
