import { useEffect, useMemo, useState } from 'react';
import { blockUser, cancelFriendRequest, respondFriendRequest, sendFriendRequest, unblockUser } from '../lib/social';
import { getPublicProfile } from '../lib/publicProfile';
import './PublicProfile.css';

const GROUP_ICONS = { designers: '✦', developers: '⌘', 'video-editors': '▣', musicians: '♫', marketers: '↗', photographers: '◉', writers: '✎', entrepreneurs: '◇' };
function initials(name = 'Favourit member') { return name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'FV'; }
function Avatar({ person, large = false }) { return person?.avatar_url ? <img className={`public-profile-avatar ${large ? 'large' : ''}`} src={person.avatar_url} alt="" /> : <div className={`public-profile-avatar ${large ? 'large' : ''}`}>{initials(person?.display_name || person?.username)}</div>; }

export default function PublicProfile({ userId, session, onClose, onMessage }) {
  const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [menuOpen, setMenuOpen] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { setProfile(await getPublicProfile(userId)); } catch (err) { setError(err.message || 'Could not load this profile.'); } finally { setLoading(false); } };
  useEffect(() => { if (userId) load(); }, [userId]);
  const action = async fn => { setBusy(true); setError(''); try { await fn(); await load(); } catch (err) { setError(err.message || 'Could not update this connection.'); } finally { setBusy(false); } };
  const friendAction = profile?.friend_status;
  const stats = profile?.stats || {};
  const isSelf = profile?.id === session?.user?.id;
  const joinedGroups = useMemo(() => Array.isArray(profile?.groups) ? profile.groups : [], [profile]);
  if (!userId) return null;
  return <div className="public-profile-overlay" onMouseDown={e => e.target === e.currentTarget && onClose?.()}><section className="public-profile-card" role="dialog" aria-modal="true" aria-labelledby="public-profile-title">
    <button className="public-profile-close" onClick={onClose} aria-label="Close profile">×</button>
    {loading ? <div className="public-profile-loading"><div className="public-profile-spinner" /><span>Loading profile…</span></div> : error ? <div className="public-profile-empty"><h2>Profile unavailable</h2><p>{error}</p><button className="secondary" onClick={load}>Try again</button></div> : <>
      <header className="public-profile-header"><div className="public-profile-identity"><Avatar person={profile} large /><div><div className="eyebrow">FAVOURIT MEMBER</div><h1 id="public-profile-title">{profile.display_name}</h1><div className="public-profile-handle">@{profile.username} {profile.is_verified && <span className="verified-badge">✓ Verified</span>}</div><p>{profile.bio || 'This member has not added a bio yet.'}</p><small>Member since {new Date(profile.created_at).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</small></div></div><div className="public-profile-header-actions">{!isSelf && <>{friendAction === 'friends' ? <span className="connection-state">Friends ✓</span> : friendAction === 'incoming' ? <><button className="primary" disabled={busy} onClick={() => action(() => respondFriendRequest(profile.id, 'accept'))}>Accept</button><button className="secondary" disabled={busy} onClick={() => action(() => respondFriendRequest(profile.id, 'reject'))}>Decline</button></> : friendAction === 'outgoing' ? <button className="secondary" disabled={busy} onClick={() => action(async () => { const graphRequest = await Promise.resolve(null); if (graphRequest) await cancelFriendRequest(graphRequest); })}>Request sent</button> : !profile.blocked_by_me && !profile.blocked_me ? <button className="primary" disabled={busy} onClick={() => action(() => sendFriendRequest(profile.id))}>Connect</button> : null}{!profile.blocked_me && <button className="secondary" disabled={busy} onClick={() => onMessage?.(profile.username)}>Message</button>}<div className="public-profile-menu-wrap"><button className="profile-more" onClick={() => setMenuOpen(v => !v)} aria-label="More actions">•••</button>{menuOpen && <div className="public-profile-menu">{profile.blocked_by_me ? <button onClick={() => action(() => unblockUser(profile.id))}>Unblock</button> : <button className="danger" onClick={() => action(() => blockUser(profile.id))}>Block</button>}<button onClick={() => { setMenuOpen(false); window.alert('Reporting a user will be available here.'); }}>Report</button></div>}</div></>}</div></header>
      {(profile.blocked_by_me || profile.blocked_me) && <div className="public-profile-notice">{profile.blocked_by_me ? 'You blocked this member. Unblock them from the ••• menu to reconnect.' : 'This member has blocked you. Some interactions are unavailable.'}</div>}
      <div className="public-profile-stats"><div><strong>{Number(stats.rating || 0).toFixed(1)}</strong><span>Rating · {stats.review_count || 0} reviews</span></div><div><strong>{stats.completed_deals || 0}</strong><span>Completed deals</span></div><div><strong>{stats.published_deals || 0}</strong><span>Services available</span></div></div>
      <section className="public-profile-section"><div className="public-profile-section-heading"><div><div className="eyebrow">SERVICES</div><h2>What {profile.display_name.split(' ')[0]} offers</h2></div><span>{profile.deals?.length || 0}</span></div>{profile.deals?.length ? <div className="public-profile-deals">{profile.deals.map(deal => <article className="public-deal-card" key={deal.id}><span className="public-deal-category">{deal.category}</span><h3>{deal.title}</h3><p>{deal.description}</p><footer><strong>{Number(deal.price_fav || 0).toLocaleString()} FAV</strong><span>{deal.delivery_days} day{deal.delivery_days === 1 ? '' : 's'}</span></footer></article>)}</div> : <div className="public-profile-muted">No public services yet.</div>}</section>
      <div className="public-profile-two-column"><section className="public-profile-section"><div className="eyebrow">REVIEWS</div><h2>Client feedback</h2>{profile.reviews?.length ? <div className="public-review-list">{profile.reviews.map(review => <article className="public-review" key={review.id}><Avatar person={review.reviewer}/><div><div className="public-review-top"><strong>{review.reviewer?.display_name || review.reviewer?.username}</strong><span>{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</span></div><p>{review.body || 'No written feedback.'}</p><small>{new Date(review.created_at).toLocaleDateString()}</small></div></article>)}</div> : <div className="public-profile-muted">No reviews yet.</div>}</section><section className="public-profile-section"><div className="eyebrow">COMMUNITY</div><h2>Skill communities</h2>{joinedGroups.length ? <div className="public-profile-groups">{joinedGroups.map(group => <div className="public-profile-group" key={group.id}><span>{GROUP_ICONS[group.slug] || '◇'}</span><div><strong>{group.name}</strong><small>{group.description}</small></div></div>)}</div> : <div className="public-profile-muted">Not a member of any public skill community yet.</div>}</section></div>
    </>}
  </section></div>;
}
