import { useEffect, useMemo, useState } from 'react';
import './App.css';
import './Prototype.css';
import { categories, deals as seedDeals } from './data/deals';
import { statusLabels } from './data/orders';
import { getMyWallet, formatFav } from './lib/wallet';
import { createOrderAndHoldFav, getMyOrders, releaseOrder, refundOrder } from './lib/orders';
import { getPublishedDeals, createDeal as createDealRemote } from './lib/deals';
import { signOut } from './lib/auth';

const navItems = ['Home', 'Explore', 'Orders', 'Community', 'Upgrade'];
const MICRO_FAV = 1000000;

function Logo(){return <div className="logo"><span>Favour</span><i>it</i></div>}
function Avatar({initials,large=false}){return <div className={large?'avatar avatar-lg':'avatar'}>{initials || 'FV'}</div>}
function initialsFor(name='Favourit seller'){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase() || 'FV'}

function DealCard({deal,onOpen}){return <article className="deal-card" onClick={()=>onOpen(deal)}><div className="deal-art"><span>{deal.category}</span><b>{deal.accent || initialsFor(deal.seller)}</b></div><div className="deal-content"><div className="seller"><Avatar initials={deal.accent || initialsFor(deal.seller)}/><div><strong>{deal.seller}</strong><small>Top seller · {deal.delivery}</small></div><span className="rating">★ {deal.rating || 'New'}</span></div><h3>{deal.title}</h3><div className="deal-bottom"><span>from <strong>{formatFav(deal.price)} FAV</strong></span><button onClick={e=>e.stopPropagation()}>♡</button></div></div></article>}

function Orders({orders,onOpen,fav}){return <section className="page-section"><div className="page-title"><div><div className="eyebrow">MY ORDERS</div><h1>Your work, <span>protected.</span></h1><p>Track every purchase from funded escrow to final delivery.</p></div><div className="wallet-mini"><small>AVAILABLE</small><strong>{formatFav(fav)} FAV</strong></div></div>{orders.length ? <div className="orders-list">{orders.map(order=><button className="order-row" key={order.id} onClick={()=>onOpen(order)}><div className="order-id">{String(order.id).slice(0,8)}</div><div className="order-info"><strong>{order.title}</strong><span>{order.seller} · {order.category}</span></div><div className="order-amount"><strong>{formatFav(order.amount)} FAV</strong><small>fee {formatFav(order.fee)} FAV</small></div><span className={`status status-${order.status}`}>{statusLabels[order.status] || order.status}</span><span className="order-arrow">→</span></button>)}</div> : <div className="empty-state"><h2>No orders yet.</h2><p>Explore the marketplace and fund your first protected FAV order.</p></div>}<div className="orders-info"><div><b>1</b><span>Payment secured in escrow</span></div><div><b>2</b><span>Seller delivers the work</span></div><div><b>3</b><span>You approve and release</span></div></div></section>}

function OrderDetail({order,onBack,onRelease,onRefund,busy}){return <section className="page-section"><button className="back-button" onClick={onBack}>← Back to Orders</button><div className="order-detail"><div className="detail-description"><div className="eyebrow">ORDER {String(order.id).slice(0,8)}</div><h1>{order.title}</h1><div className="seller detail-seller"><Avatar initials={initialsFor(order.seller)} large/><div><strong>{order.seller}</strong><small>{order.category} · Favourit seller</small></div></div><div className="timeline"><div className="timeline-item done"><b>Payment secured</b><span>FAV is held in escrow</span></div><div className={`timeline-item ${['in_progress','delivered','completed'].includes(order.status)?'done':''}`}><b>Work in progress</b><span>Seller is working on your order</span></div><div className={`timeline-item ${['delivered','completed'].includes(order.status)?'done':''}`}><b>Delivery</b><span>Review the seller's delivery</span></div><div className={`timeline-item ${order.status==='completed'?'done':''}`}><b>Completed</b><span>FAV is released to the seller</span></div></div></div><aside className="buy-card order-side"><div className="eyebrow">ORDER STATUS</div><span className={`status status-${order.status}`}>{statusLabels[order.status] || order.status}</span><h2>{formatFav(order.amount)} <em>FAV</em></h2><div className="order-breakdown"><span>Service <b>{formatFav(order.amount)} FAV</b></span><span>Platform fee <b>{formatFav(order.fee)} FAV</b></span><span>Total held <b>{formatFav(order.amount)} FAV</b></span></div>{!['completed','cancelled'].includes(order.status)&&<><button className="primary full" disabled={busy} onClick={onRelease}>{busy?'Processing…':'Approve & release FAV'}</button><button className="secondary full" disabled={busy} onClick={onRefund}>Request refund</button></>}<small className="escrow-note">◈ FAV remains protected until a release or approved refund.</small></aside></div></section>}

function Explore({query,setQuery,onOpen,onCreate,deals}){const filtered=useMemo(()=>{const v=query.trim().toLowerCase();return v?deals.filter(d=>`${d.title} ${d.category} ${d.seller}`.toLowerCase().includes(v)):deals},[query,deals]);return <section className="page-section"><div className="page-title"><div><div className="eyebrow">MARKETPLACE</div><h1>Find your next <span>favourite.</span></h1><p>Browse skills, services and ideas from people in the Favourit community.</p></div><button className="primary" onClick={onCreate}>+ Offer a skill</button></div><div className="search-row"><div className="search-box">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search deals, skills or people..."/></div><button className="filter-button">Filters <span>☷</span></button></div><div className="category-row">{['All',...categories].map(c=><button key={c} className={query===(c==='All'?'':c)?'category selected':'category'} onClick={()=>setQuery(c==='All'?'':c)}>{c}</button>)}</div><div className="results-meta"><span>{filtered.length} deals available</span><button>Sort: Recommended ▾</button></div><div className="deal-grid wide-grid">{filtered.map(d=><DealCard key={d.id} deal={d} onOpen={onOpen}/>)}</div></section>}

function DealDetail({deal,onBack,onBuy,fav,busy}){if(!deal)return null;return <section className="page-section"><button className="back-button" onClick={onBack}>← Back to Explore</button><div className="detail-layout"><div><div className="detail-art"><span>{deal.category}</span><strong>{deal.accent || initialsFor(deal.seller)}</strong></div><div className="detail-description"><div className="seller detail-seller"><Avatar initials={deal.accent || initialsFor(deal.seller)} large/><div><strong>{deal.seller}</strong><small>Top seller · ★ {deal.rating || 'New'} · {deal.reviews || 0} reviews</small></div></div><h1>{deal.title}</h1><p>{deal.description || 'Get a polished, reliable result from an experienced Favourit creator. Everything is handled inside Favourit with protected payment and clear delivery expectations.'}</p><div className="detail-stats"><span>⚡ {deal.delivery} delivery</span><span>★ {deal.rating || 'New'} rating</span><span>◈ Escrow protected</span></div></div></div><aside className="buy-card"><div className="eyebrow">STANDARD PACKAGE</div><h2>{formatFav(deal.price)} <em>FAV</em></h2><p>One complete delivery · protected payment</p><button className="primary full" disabled={busy} onClick={onBuy}>{busy?'Funding escrow…':`Continue — ${formatFav(deal.price)} FAV`}</button><div className="balance-note">Your balance: <strong>{formatFav(fav)} FAV</strong></div><hr/><div className="included"><span>✓ Payment held in escrow</span><span>✓ Secure messages</span><span>✓ Dispute protection</span></div></aside></div></section>}

function CreateDeal({onBack,onCreated,busy}){const [form,setForm]=useState({title:'',category:'',description:'',price:'',delivery:'3 days'});const update=(key,value)=>setForm(v=>({...v,[key]:value}));return <section className="page-section"><button className="back-button" onClick={onBack}>← Back</button><div className="form-header"><div className="eyebrow">CREATE A DEAL</div><h1>Turn your skill into <span>FAV.</span></h1><p>Tell the community what you can do. Keep it clear, specific and easy to buy.</p></div><div className="form-card"><label>Deal title<input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="I will..."/></label><label>Category<select value={form.category} onChange={e=>update('category',e.target.value)}><option value="">Select a category</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e=>update('description',e.target.value)} rows="5" placeholder="Describe what the buyer will receive..."/></label><div className="form-two"><label>Price in FAV<input value={form.price} onChange={e=>update('price',e.target.value)} type="number" min="0.01" step="0.01" placeholder="250"/></label><label>Delivery time<select value={form.delivery} onChange={e=>update('delivery',e.target.value)}><option>1 day</option><option>2 days</option><option>3 days</option><option>5 days</option><option>7 days</option></select></label></div><div className="upload-box">＋ <strong>Add attachments</strong><small>Attachments will be connected to storage in the next backend pass.</small></div><div className="form-actions"><button className="secondary" onClick={onBack}>Cancel</button><button className="primary" disabled={busy||!form.title.trim()||!form.category||!form.description.trim()||!form.price} onClick={()=>onCreated(form)}>{busy?'Publishing…':'Publish deal →'}</button></div></div></section>}

function Home({fav,onExplore,onCreate,rewardMessage}){return <section className="page-section home-page"><div className="hero"><div><div className="eyebrow">WELCOME TO FAVOURIT</div><h1>Your skills are your <span>currency.</span></h1><p>Offer what you know, earn FAV, and use it to access skills from the rest of the community — with every purchase protected by escrow.</p><div className="hero-actions"><button className="primary" onClick={onExplore}>Explore marketplace →</button><button className="secondary" onClick={onCreate}>Offer a skill</button></div>{rewardMessage&&<div className="reward-banner">✦ {rewardMessage}</div>}</div><div className="hero-orb"><strong>{formatFav(fav)}</strong><span>FAV AVAILABLE</span></div></div><div className="value-grid"><div><b>◈</b><h3>You are secured</h3><p>Payments stay protected in escrow until the order is completed.</p></div><div><b>↔</b><h3>Dealmaking</h3><p>Turn any legitimate skill into something another member can buy.</p></div><div><b>✦</b><h3>Use our coin</h3><p>FAV moves through the marketplace as purchasing power.</p></div></div></section>}

function Community(){return <section className="page-section"><div className="page-title"><div><div className="eyebrow">COMMUNITY</div><h1>People make <span>Favourit.</span></h1><p>Connect with creators, friends and groups around the skills you care about.</p></div><button className="secondary">Find people</button></div><div className="community-grid"><div className="community-card"><div className="community-icon">♢</div><h2>Friends</h2><p>Follow great sellers and keep up with the people you trust.</p><button className="text-button">View friends →</button></div><div className="community-card featured"><div className="community-icon">✦</div><h2>Groups</h2><p>Join conversations around design, code, business, music and more.</p><button className="text-button">Explore groups →</button></div><div className="community-card"><div className="community-icon">☷</div><h2>Messages</h2><p>Talk directly with buyers and sellers before and during every deal.</p><button className="text-button">Open inbox →</button></div></div></section>}

function Premium({fav}){return <section className="page-section premium-page"><div className="premium-hero"><div><div className="eyebrow">FAVOURIT PREMIUM</div><h1>More FAV.<br/><span>More possibilities.</span></h1><p>Unlock a stronger daily reward, better visibility and tools that help you get more from the marketplace.</p><button className="primary">Upgrade to Premium →</button></div><div className="premium-orb"><strong>+2</strong><span>VALUE / DAY</span></div></div><div className="premium-grid"><div><b>✦</b><h3>Higher daily FAV</h3><p>Get a boosted daily reward while keeping the economy sustainable.</p></div><div><b>↗</b><h3>More visibility</h3><p>Give your deals better placement and reach more buyers.</p></div><div><b>◈</b><h3>Lower fees</h3><p>Keep more of the FAV you earn from completed work.</p></div><div><b>⌁</b><h3>Premium badge</h3><p>Show the community that you are a committed Favourit member.</p></div></div><div className="wallet-strip"><span>Current wallet</span><strong>{formatFav(fav)} FAV</strong><small>Reward is calculated from the current FAV economic reference value.</small></div></section>}

function Profile({fav,deals,orders,onCreate,onOrders,session,onSignOut}){const name=session?.user?.user_metadata?.display_name || session?.user?.email?.split('@')[0] || 'Favourit member';const initials=initialsFor(name);return <section className="page-section"><div className="profile-hero"><div className="profile-main"><Avatar initials={initials} large/><div><div className="eyebrow">YOUR PROFILE</div><h1>{name}</h1><p>Creator · Buyer · Favourit member</p><div className="profile-tags"><span>✓ Account verified</span><span>◈ Favourit member</span></div></div></div><button className="secondary" onClick={onSignOut}>Sign out</button></div><div className="profile-stats"><div><small>FAV BALANCE</small><strong>{formatFav(fav)}</strong><span>FAV</span></div><div><small>DEALS PUBLISHED</small><strong>{deals.filter(d=>d.sellerId===session?.user?.id).length}</strong><span>services</span></div><div><small>ORDERS</small><strong>{orders.length}</strong><span>purchases</span></div><div><small>ACCOUNT</small><strong>Active</strong><span>member</span></div></div><div className="profile-grid"><div className="profile-panel"><div className="panel-heading"><h2>Wallet</h2></div><div className="transaction"><span className="tx-icon positive">+</span><div><strong>Available FAV</strong><small>Live wallet balance</small></div><b>{formatFav(fav)} FAV</b></div></div><div className="profile-panel"><div className="panel-heading"><h2>Orders</h2></div><p className="panel-copy">Your purchases are funded through protected FAV escrow.</p><button className="primary full" onClick={onOrders}>View my orders →</button><button className="secondary full" onClick={onCreate}>Offer a new skill →</button></div></div></section>}

function App({initialWallet,session,rewardMessage}){
  const [active,setActive]=useState('Home');
  const [query,setQuery]=useState('');
  const [fav,setFav]=useState(Number(initialWallet?.available_fav || 0)/MICRO_FAV);
  const [selectedDeal,setSelectedDeal]=useState(null);
  const [selectedOrder,setSelectedOrder]=useState(null);
  const [toast,setToast]=useState('');
  const [deals,setDeals]=useState(seedDeals);
  const [orders,setOrders]=useState([]);
  const [busy,setBusy]=useState(false);
  const [loading,setLoading]=useState(true);

  const notify=message=>{setToast(message);window.clearTimeout(window.__favouritToast);window.__favouritToast=window.setTimeout(()=>setToast(''),3200)};
  const go=item=>{setSelectedDeal(null);setSelectedOrder(null);setActive(item);window.scrollTo({top:0,behavior:'smooth'})};
  const refreshWallet=async()=>{const wallet=await getMyWallet();if(wallet)setFav(Number(wallet.available_fav || 0)/MICRO_FAV);return wallet};

  useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);try{const [remoteDeals,remoteOrders,wallet]=await Promise.all([getPublishedDeals(),getMyOrders(),getMyWallet()]);if(cancelled)return;if(remoteDeals.length)setDeals(remoteDeals);setOrders(remoteOrders);setFav(Number(wallet?.available_fav || 0)/MICRO_FAV);}catch(error){if(!cancelled)notify(error.message || 'Could not load your Favourit data.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  useEffect(()=>{if(rewardMessage)notify(rewardMessage)},[rewardMessage]);

  const buy=async()=>{if(!selectedDeal||busy)return;setBusy(true);try{const order=await createOrderAndHoldFav(selectedDeal.id);await refreshWallet();const freshOrders=await getMyOrders();setOrders(freshOrders);const fresh= freshOrders.find(o=>o.id===order?.id) || order;if(!fresh)throw new Error('Order was funded but could not be loaded.');setSelectedDeal(null);setSelectedOrder(fresh);setActive('Orders');notify(`Order funded — ${formatFav(fresh.amount)} FAV moved to escrow.`)}catch(error){notify(error.message || 'Could not fund this order.')}finally{setBusy(false)}};
  const release=async()=>{if(!selectedOrder||busy)return;setBusy(true);try{await releaseOrder(selectedOrder.id);const freshOrders=await getMyOrders();setOrders(freshOrders);setSelectedOrder(freshOrders.find(o=>o.id===selectedOrder.id)||{...selectedOrder,status:'completed'});await refreshWallet();notify('Order completed — escrow released to the seller.')}catch(error){notify(error.message || 'Could not release escrow.')}finally{setBusy(false)}};
  const refund=async()=>{if(!selectedOrder||busy)return;setBusy(true);try{await refundOrder(selectedOrder.id);const freshOrders=await getMyOrders();setOrders(freshOrders);setSelectedOrder(freshOrders.find(o=>o.id===selectedOrder.id)||{...selectedOrder,status:'cancelled'});await refreshWallet();notify('Refund processed — held FAV returned to your wallet.')}catch(error){notify(error.message || 'Could not process refund.')}finally{setBusy(false)}};
  const publish=async form=>{if(busy)return;setBusy(true);try{const deal=await createDealRemote(form);setDeals(v=>[deal,...v]);notify('Deal published to the Favourit marketplace.');go('Explore')}catch(error){notify(error.message || 'Could not publish your deal.')}finally{setBusy(false)}};
  const logout=async()=>{try{await signOut()}catch(error){notify(error.message || 'Could not sign out.')}};

  const content=active==='Home'?<Home fav={fav} onExplore={()=>go('Explore')} onCreate={()=>go('Create Deal')} rewardMessage={rewardMessage}/>:active==='Explore'?<Explore query={query} setQuery={setQuery} onOpen={setSelectedDeal} onCreate={()=>go('Create Deal')} deals={deals}/>:active==='Orders'?<Orders orders={orders} onOpen={setSelectedOrder} fav={fav}/>:active==='Community'?<Community/>:active==='Upgrade'?<Premium fav={fav}/>:active==='Profile'?<Profile fav={fav} deals={deals} orders={orders} onCreate={()=>go('Create Deal')} onOrders={()=>go('Orders')} session={session} onSignOut={logout}/>:active==='Create Deal'?<CreateDeal onBack={()=>go('Explore')} onCreated={publish} busy={busy}/>:<Home fav={fav} onExplore={()=>go('Explore')} onCreate={()=>go('Create Deal')}/>;

  return <div className="app-shell"><header className="topbar"><button className="brand-button" onClick={()=>go('Home')}><Logo/></button><nav>{navItems.map(item=><button key={item} className={active===item?'active':''} onClick={()=>go(item)}>{item}</button>)}</nav><div className="top-actions"><div className="balance"><small>FAV</small><strong>{formatFav(fav)}</strong></div><button className="profile-button" onClick={()=>go('Profile')}>{initialsFor(session?.user?.user_metadata?.display_name || session?.user?.email)} <span>⌄</span></button></div></header><main>{loading?<div className="loading-state">Loading your Favourit account…</div>:content}</main>{selectedDeal&&<DealDetail deal={selectedDeal} fav={fav} onBack={()=>setSelectedDeal(null)} onBuy={buy} busy={busy}/>} {selectedOrder&&<OrderDetail order={selectedOrder} onBack={()=>setSelectedOrder(null)} onRelease={release} onRefund={refund} busy={busy}/>} {toast&&<div className="toast">{toast}</div>}</div>
}

export default App;
