import { useEffect, useMemo, useState } from 'react';
import './App.css';
import './Prototype.css';
import { categories, deals as seedDeals } from './data/deals';
import { statusLabels } from './data/orders';
import { getMyWallet, formatFav } from './lib/wallet';
import { createOrderAndHoldFav, getMyOrders, releaseOrder, refundOrder } from './lib/orders';
import { getPublishedDeals, createDeal as createDealRemote } from './lib/deals';
import { signOut } from './lib/auth';
import { startOrder, deliverOrder } from './lib/sellerOrders';
import { getMyFavoriteDealIds, setFavorite } from './lib/favorites';
import { getDealReviews, createReview } from './lib/reviews';
import { getOrderStatusHistory } from './lib/orderHistory';
import { getOrCreateOrderConversation } from './lib/messaging';
import { getMyPremiumMembership, isPremiumActive } from './lib/premium';

const navItems = ['Home', 'Explore', 'Orders', 'Community', 'Upgrade'];
const initialsFor = (name = 'Favourit seller') => name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'FV';
const Logo = () => <div className="logo"><span>Favour</span><i>it</i></div>;
const Avatar = ({ initials, large = false }) => <div className={large ? 'avatar avatar-lg' : 'avatar'}>{initials || 'FV'}</div>;

function DealCard({ deal, onOpen, favorite, onFavorite }) {
  return <article className="deal-card" onClick={() => onOpen(deal)}>
    <div className="deal-art"><span>{deal.category}</span><b>{deal.accent || initialsFor(deal.seller)}</b></div>
    <div className="deal-content"><div className="seller"><Avatar initials={deal.accent || initialsFor(deal.seller)} /><div><strong>{deal.seller}</strong><small>Top seller · {deal.delivery}</small></div><span className="rating">★ {deal.rating || 'New'}</span></div>
      <h3>{deal.title}</h3><div className="deal-bottom"><span>from <strong>{formatFav(deal.price * 1000000)} FAV</strong></span><button aria-label="Favorite" className={favorite ? 'favorite active' : 'favorite'} onClick={e => { e.stopPropagation(); onFavorite(deal.id); }}>{favorite ? '♥' : '♡'}</button></div>
    </div>
  </article>;
}

function Explore({ query, setQuery, category, setCategory, onOpen, onCreate, deals, favorites, onFavorite }) {
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return deals.filter(d => (!category || d.category === category) && (!q || `${d.title} ${d.category} ${d.seller}`.toLowerCase().includes(q)));
  }, [query, category, deals]);
  return <section className="page-section"><div className="page-title"><div><div className="eyebrow">MARKETPLACE</div><h1>Find your next <span>favourite.</span></h1><p>Browse skills, services and ideas from people in the Favourit community.</p></div><button className="primary" onClick={onCreate}>+ Offer a skill</button></div>
    <div className="search-row"><div className="search-box">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search deals, skills or people..." /></div><button className="filter-button">Filters <span>☷</span></button></div>
    <div className="category-row"><button className={!category ? 'category selected' : 'category'} onClick={() => setCategory('')}>All</button>{categories.map(c => <button key={c} className={category === c ? 'category selected' : 'category'} onClick={() => setCategory(c)}>{c}</button>)}</div>
    <div className="results-meta"><span>{filtered.length} deals available</span><span>{favorites.size} saved</span></div><div className="deal-grid wide-grid">{filtered.map(d => <DealCard key={d.id} deal={d} onOpen={onOpen} favorite={favorites.has(d.id)} onFavorite={onFavorite} />)}</div>
    {!filtered.length && <div className="empty-state"><h2>No matching deals.</h2><p>Try another search or category.</p></div>}
  </section>;
}

function DealDetail({ deal, onBack, onBuy, fav, busy, favorites, onFavorite }) {
  const [reviews, setReviews] = useState([]);
  useEffect(() => { let active = true; if (deal?.sellerId) getDealReviews(deal.sellerId).then(v => active && setReviews(v)).catch(() => {}); return () => { active = false; }; }, [deal]);
  if (!deal) return null;
  return <section className="page-section"><button className="back-button" onClick={onBack}>← Back to Explore</button><div className="detail-layout"><div><div className="detail-art"><span>{deal.category}</span><strong>{deal.accent || initialsFor(deal.seller)}</strong></div><div className="detail-description"><div className="seller detail-seller"><Avatar initials={deal.accent || initialsFor(deal.seller)} large /><div><strong>{deal.seller}</strong><small>Top seller · ★ {deal.rating || 'New'} · {deal.reviews || reviews.length} reviews</small></div><button className="secondary" onClick={() => onFavorite(deal.id)}>{favorites.has(deal.id) ? '♥ Saved' : '♡ Save'}</button></div><h1>{deal.title}</h1><p>{deal.description || 'A clear, reliable Favourit service with protected payment and defined delivery.'}</p><div className="detail-stats"><span>⚡ {deal.delivery} delivery</span><span>★ {deal.rating || 'New'} rating</span><span>◈ Escrow protected</span></div><div className="reviews-block"><h2>Reviews</h2>{reviews.length ? reviews.slice(0, 5).map(r => <div className="review-row" key={r.id}><b>★ {r.rating}</b><span>{r.body || 'Great experience.'}</span><small>— {r.reviewer}</small></div>) : <p>No reviews yet.</p>}</div></div></div><aside className="buy-card"><div className="eyebrow">STANDARD PACKAGE</div><h2>{formatFav(deal.price * 1000000)} <em>FAV</em></h2><p>One complete delivery · protected payment</p><button className="primary full" disabled={busy} onClick={onBuy}>{busy ? 'Funding escrow…' : `Continue — ${formatFav(deal.price * 1000000)} FAV`}</button><div className="balance-note">Your balance: <strong>{formatFav(fav)} FAV</strong></div><hr /><div className="included"><span>✓ Payment held in escrow</span><span>✓ Secure messages</span><span>✓ Dispute protection</span></div></aside></div></section>;
}

function OrderDetail({ order, session, onBack, onRelease, onRefund, onStart, onDeliver, onChat, busy, onReviewed }) {
  const isBuyer = order.buyerId === session?.user?.id; const isSeller = order.sellerId === session?.user?.id;
  const [history, setHistory] = useState([]); const [rating, setRating] = useState(5); const [body, setBody] = useState(''); const [reviewed, setReviewed] = useState(false);
  useEffect(() => { getOrderStatusHistory(order.id).then(setHistory).catch(() => {}); }, [order.id]);
  const submitReview = async e => { e.preventDefault(); try { await createReview({ orderId: order.id, rating, body }); setReviewed(true); onReviewed?.(); } catch (error) { window.dispatchEvent(new CustomEvent('favourit:toast', { detail: error.message })); } };
  return <section className="page-section"><button className="back-button" onClick={onBack}>← Back to Orders</button><div className="order-detail"><div className="detail-description"><div className="eyebrow">ORDER {String(order.id).slice(0, 8)}</div><h1>{order.title}</h1><div className="seller detail-seller"><Avatar initials={initialsFor(order.seller)} large /><div><strong>{order.seller}</strong><small>{order.category} · Favourit member</small></div></div><div className="timeline"><div className="timeline-item done"><b>Payment secured</b><span>FAV is held in escrow</span></div><div className={`timeline-item ${['in_progress','delivered','completed'].includes(order.status) ? 'done' : ''}`}><b>Work in progress</b><span>Seller is working on your order</span></div><div className={`timeline-item ${['delivered','completed'].includes(order.status) ? 'done' : ''}`}><b>Delivery</b><span>Review the seller's delivery</span></div><div className={`timeline-item ${order.status === 'completed' ? 'done' : ''}`}><b>Completed</b><span>FAV is released to the seller</span></div></div>{history.length > 1 && <div className="order-history"><h3>Order history</h3>{history.map(h => <div key={h.id}><span>{statusLabels[h.to_status] || h.to_status}</span><small>{new Date(h.created_at).toLocaleString()}</small></div>)}</div>}</div><aside className="buy-card order-side"><div className="eyebrow">ORDER STATUS</div><span className={`status status-${order.status}`}>{statusLabels[order.status] || order.status}</span><h2>{formatFav(order.amount * 1000000)} <em>FAV</em></h2><div className="order-breakdown"><span>Service <b>{formatFav(order.amount * 1000000)} FAV</b></span><span>Platform fee <b>{formatFav(order.fee * 1000000)} FAV</b></span></div>
      <button className="secondary full" onClick={onChat}>Open order messages</button>
      {isSeller && order.status === 'funded' && <button className="primary full" disabled={busy} onClick={onStart}>Start work</button>}
      {isSeller && ['funded','in_progress'].includes(order.status) && <button className="primary full" disabled={busy} onClick={onDeliver}>Mark delivered</button>}
      {isBuyer && order.status === 'delivered' && <button className="primary full" disabled={busy} onClick={onRelease}>Approve & release FAV</button>}
      {isBuyer && ['funded','in_progress','delivered'].includes(order.status) && <button className="secondary full" disabled={busy} onClick={onRefund}>Open refund dispute</button>}
      {isBuyer && order.status === 'completed' && !reviewed && <form className="review-form" onSubmit={submitReview}><h3>Leave a review</h3><div className="star-picker">{[1,2,3,4,5].map(n => <button type="button" key={n} className={n <= rating ? 'selected' : ''} onClick={() => setRating(n)}>★</button>)}</div><textarea value={body} onChange={e => setBody(e.target.value)} maxLength={1000} placeholder="How was the experience?" /><button className="primary full">Publish review</button></form>}
      {reviewed && <div className="success-note">✓ Review published. Thanks for helping the community.</div>}<small className="escrow-note">◈ FAV remains protected until release or an approved dispute resolution.</small></aside></div></section>;
}

function Orders({ orders, onOpen, fav, session }) { const purchases = orders.filter(o => o.buyerId === session?.user?.id); const sales = orders.filter(o => o.sellerId === session?.user?.id); const list = [...purchases, ...sales.filter(o => !purchases.some(p => p.id === o.id))]; return <section className="page-section"><div className="page-title"><div><div className="eyebrow">MY ORDERS</div><h1>Your work, <span>protected.</span></h1><p>Purchases and sales, all protected by FAV escrow.</p></div><div className="wallet-mini"><small>AVAILABLE</small><strong>{formatFav(fav)} FAV</strong></div></div>{list.length ? <div className="orders-list">{list.map(order => <button className="order-row" key={order.id} onClick={() => onOpen(order)}><div className="order-id">{String(order.id).slice(0,8)}</div><div className="order-info"><strong>{order.title}</strong><span>{order.seller} · {order.category}</span></div><div className="order-amount"><strong>{formatFav(order.amount * 1000000)} FAV</strong><small>{order.sellerId === session?.user?.id ? 'sale' : 'purchase'}</small></div><span className={`status status-${order.status}`}>{statusLabels[order.status] || order.status}</span><span className="order-arrow">→</span></button>)}</div> : <div className="empty-state"><h2>No orders yet.</h2><p>Explore the marketplace and fund your first protected FAV order.</p></div>}</section>; }

function CreateDeal({ onBack, onCreated, busy }) { const [form, setForm] = useState({title:'',category:'',description:'',price:'',delivery:'3 days'}); const update=(k,v)=>setForm(x=>({...x,[k]:v})); return <section className="page-section"><button className="back-button" onClick={onBack}>← Back</button><div className="form-header"><div className="eyebrow">CREATE A DEAL</div><h1>Turn your skill into <span>FAV.</span></h1><p>Tell the community what you can do. Keep it clear, specific and easy to buy.</p></div><div className="form-card"><label>Deal title<input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="I will..." /></label><label>Category<select value={form.category} onChange={e=>update('category',e.target.value)}><option value="">Select a category</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e=>update('description',e.target.value)} rows="5" placeholder="Describe what the buyer will receive..." /></label><div className="form-two"><label>Price in FAV<input value={form.price} onChange={e=>update('price',e.target.value)} type="number" min="0.01" step="0.01" placeholder="250" /></label><label>Delivery time<select value={form.delivery} onChange={e=>update('delivery',e.target.value)}><option>1 day</option><option>2 days</option><option>3 days</option><option>5 days</option><option>7 days</option></select></label></div><div className="upload-box">✓ <strong>Secure delivery</strong><small>Order files can be shared through the protected order conversation.</small></div><div className="form-actions"><button className="secondary" onClick={onBack}>Cancel</button><button className="primary" disabled={busy||!form.title.trim()||!form.category||!form.description.trim()||!form.price} onClick={()=>onCreated(form)}>{busy?'Publishing…':'Publish deal →'}</button></div></div></section>; }

function Community({ onChat }) { return <section className="page-section"><div className="page-title"><div><div className="eyebrow">COMMUNITY</div><h1>People make <span>Favourit.</span></h1><p>Build relationships around the skills and services you care about.</p></div><button className="secondary" onClick={onChat}>Open messages</button></div><div className="community-grid"><div className="community-card"><div className="community-icon">♢</div><h2>Friends</h2><p>Save great sellers and keep the people you trust close.</p><button className="text-button" onClick={onChat}>Start a conversation →</button></div><div className="community-card featured"><div className="community-icon">✦</div><h2>Groups</h2><p>Community groups are the next social layer built on top of the marketplace.</p><span className="status status-pending">Coming next</span></div><div className="community-card"><div className="community-icon">☷</div><h2>Messages</h2><p>Order conversations keep buyers and sellers connected through delivery.</p><button className="text-button" onClick={onChat}>Open inbox →</button></div></div></section>; }

function Premium({ fav, membership }) { const active=isPremiumActive(membership); return <section className="page-section premium-page"><div className="premium-hero"><div><div className="eyebrow">FAVOURIT PREMIUM</div><h1>More FAV.<br/><span>More possibilities.</span></h1><p>Unlock a stronger daily reward, better visibility and tools that help you get more from the marketplace.</p>{active ? <div className="success-note">✓ Premium active until {new Date(membership.active_until).toLocaleDateString()}</div> : <button className="primary" onClick={() => window.dispatchEvent(new CustomEvent('favourit:toast', {detail:'Premium checkout is not connected yet.'}))}>Upgrade to Premium →</button>}</div><div className="premium-orb"><strong>+2</strong><span>VALUE / DAY</span></div></div><div className="premium-grid"><div><b>✦</b><h3>Higher daily FAV</h3><p>Boosted daily reward while keeping the economy sustainable.</p></div><div><b>↗</b><h3>More visibility</h3><p>Give your deals better placement and reach more buyers.</p></div><div><b>◈</b><h3>Lower fees</h3><p>Keep more of the FAV you earn from completed work.</p></div><div><b>⌁</b><h3>Premium badge</h3><p>Show the community that you are a committed member.</p></div></div><div className="wallet-strip"><span>Current wallet</span><strong>{formatFav(fav)} FAV</strong><small>Rewards are calculated from the current FAV economic reference value.</small></div></section>; }

function Home({ fav, onExplore, onCreate, rewardMessage }) { return <section className="page-section home-page"><div className="hero"><div><div className="eyebrow">WELCOME TO FAVOURIT</div><h1>Your skills are your <span>currency.</span></h1><p>Offer what you know, earn FAV, and use it to access skills from the rest of the community — with every purchase protected by escrow.</p><div className="hero-actions"><button className="primary" onClick={onExplore}>Explore marketplace →</button><button className="secondary" onClick={onCreate}>Offer a skill</button></div>{rewardMessage&&<div className="reward-banner">✦ {rewardMessage}</div>}</div><div className="hero-orb"><strong>{formatFav(fav)}</strong><span>FAV AVAILABLE</span></div></div><div className="value-grid"><div><b>◈</b><h3>You are secured</h3><p>Payments stay protected in escrow until the order is completed.</p></div><div><b>↔</b><h3>Dealmaking</h3><p>Turn any legitimate skill into something another member can buy.</p></div><div><b>✦</b><h3>Use our coin</h3><p>FAV moves through the marketplace as purchasing power.</p></div></div></section>; }

function Profile({ fav, deals, orders, onCreate, onOrders, session, onSignOut }) { const name=session?.user?.user_metadata?.display_name || session?.user?.email?.split('@')[0] || 'Favourit member'; return <section className="page-section"><div className="profile-hero"><div className="profile-main"><Avatar initials={initialsFor(name)} large /><div><div className="eyebrow">YOUR PROFILE</div><h1>{name}</h1><p>Creator · Buyer · Favourit member</p><div className="profile-tags"><span>✓ Account verified</span><span>◈ Favourit member</span></div></div></div><button className="secondary" onClick={onSignOut}>Sign out</button></div><div className="profile-stats"><div><small>FAV BALANCE</small><strong>{formatFav(fav)}</strong><span>FAV</span></div><div><small>DEALS PUBLISHED</small><strong>{deals.filter(d=>d.sellerId===session?.user?.id).length}</strong><span>services</span></div><div><small>ORDERS</small><strong>{orders.length}</strong><span>purchases/sales</span></div><div><small>ACCOUNT</small><strong>Active</strong><span>member</span></div></div><div className="profile-grid"><div className="profile-panel"><div className="panel-heading"><h2>Wallet</h2></div><div className="transaction"><span className="tx-icon positive">+</span><div><strong>Available FAV</strong><small>Live wallet balance</small></div><b>{formatFav(fav)} FAV</b></div></div><div className="profile-panel"><div className="panel-heading"><h2>Orders</h2></div><p className="panel-copy">Purchases and sales use protected FAV escrow.</p><button className="primary full" onClick={onOrders}>View orders →</button><button className="secondary full" onClick={onCreate}>Offer a new skill →</button></div></div></section>; }

export default function App({ initialWallet, session, rewardMessage }) {
  const [active,setActive]=useState('Home'); const [query,setQuery]=useState(''); const [category,setCategory]=useState(''); const [fav,setFav]=useState(Number(initialWallet?.available_fav||0));
  const [deals,setDeals]=useState(seedDeals); const [orders,setOrders]=useState([]); const [favorites,setFavorites]=useState(new Set()); const [selectedDeal,setSelectedDeal]=useState(null); const [selectedOrder,setSelectedOrder]=useState(null); const [premium,setPremium]=useState(null); const [toast,setToast]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
  const notify=message=>{setToast(message); window.clearTimeout(window.__favouritToast); window.__favouritToast=window.setTimeout(()=>setToast(''),3200);};
  const go=item=>{setSelectedDeal(null);setSelectedOrder(null);setActive(item);window.scrollTo({top:0,behavior:'smooth'});};
  const refresh=async()=>{const [w,o,d,f,p]=await Promise.all([getMyWallet(),getMyOrders(),getPublishedDeals(),getMyFavoriteDealIds(),getMyPremiumMembership()]); if(w)setFav(Number(w.available_fav||0));setOrders(o);if(d.length)setDeals(d);setFavorites(f);setPremium(p);};
  useEffect(()=>{let cancelled=false;(async()=>{try{await refresh();}catch(e){if(!cancelled)notify(e.message||'Could not load your Favourit data.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  useEffect(()=>{const h=e=>notify(e.detail||'Something went wrong.');window.addEventListener('favourit:toast',h);return()=>window.removeEventListener('favourit:toast',h)},[]);
  const toggleFavorite=async id=>{const next=!favorites.has(id);setFavorites(current=>{const copy=new Set(current);next?copy.add(id):copy.delete(id);return copy});try{await setFavorite(id,next)}catch(e){setFavorites(current=>{const copy=new Set(current);next?copy.delete(id):copy.add(id);return copy});notify(e.message||'Could not update saved deal.')}};
  const buy=async()=>{if(!selectedDeal||busy)return;setBusy(true);try{const order=await createOrderAndHoldFav(selectedDeal.id);await refresh();setSelectedDeal(null);setSelectedOrder(order);setActive('Orders');notify(`Order funded — ${formatFav(order.amount*1000000)} FAV moved to escrow.`)}catch(e){notify(e.message||'Could not fund this order.')}finally{setBusy(false)}};
  const reloadOrder=async id=>{const o=await getMyOrders();setOrders(o);return o.find(x=>x.id===id)||null;};
  const release=async()=>{if(!selectedOrder||busy)return;setBusy(true);try{await releaseOrder(selectedOrder.id);const fresh=await reloadOrder(selectedOrder.id);await getMyWallet().then(w=>setFav(Number(w?.available_fav||0)));setSelectedOrder(fresh||{...selectedOrder,status:'completed'});notify('Order completed — escrow released to the seller.')}catch(e){notify(e.message||'Could not release escrow.')}finally{setBusy(false)}};
  const refund=async()=>{if(!selectedOrder||busy)return;setBusy(true);try{await refundOrder(selectedOrder.id);const fresh=await reloadOrder(selectedOrder.id);setSelectedOrder(fresh||{...selectedOrder,status:'disputed'});notify('Refund request opened — the order is now in dispute review.')}catch(e){notify(e.message||'Could not open refund dispute.')}finally{setBusy(false)}};
  const sellerAction=async action=>{if(!selectedOrder||busy)return;setBusy(true);try{await action(selectedOrder.id);const fresh=await reloadOrder(selectedOrder.id);setSelectedOrder(fresh);notify(action===startOrder?'Work started.':'Delivery marked complete for review.')}catch(e){notify(e.message||'Could not update the order.')}finally{setBusy(false)}};
  const openChat=async()=>{if(!selectedOrder)return;try{const conversation=await getOrCreateOrderConversation(selectedOrder.id);window.dispatchEvent(new CustomEvent('favourit:open-conversation',{detail:conversation}));}catch(e){notify(e.message||'Could not open messages.')}};
  const publish=async form=>{if(busy)return;setBusy(true);try{const deal=await createDealRemote(form);setDeals(v=>[deal,...v]);notify('Deal published to the Favourit marketplace.');go('Explore')}catch(e){notify(e.message||'Could not publish your deal.')}finally{setBusy(false)}};
  if(loading)return <div className="app-loading"><div><Logo/><p>Loading your Favourit account…</p></div></div>;
  let content;
  if(active==='Home')content=<Home fav={fav} onExplore={()=>go('Explore')} onCreate={()=>go('Create Deal')} rewardMessage={rewardMessage}/>;
  else if(active==='Explore')content=<Explore query={query} setQuery={setQuery} category={category} setCategory={setCategory} onOpen={setSelectedDeal} onCreate={()=>go('Create Deal')} deals={deals} favorites={favorites} onFavorite={toggleFavorite}/>;
  else if(active==='Orders')content=<Orders orders={orders} onOpen={setSelectedOrder} fav={fav} session={session}/>;
  else if(active==='Community')content=<Community onChat={()=>notify('Open a conversation from an order to start messaging securely.')}/>;
  else if(active==='Upgrade')content=<Premium fav={fav} membership={premium}/>;
  else if(active==='Profile')content=<Profile fav={fav} deals={deals} orders={orders} onCreate={()=>go('Create Deal')} onOrders={()=>go('Orders')} session={session} onSignOut={async()=>{try{await signOut()}catch(e){notify(e.message)}}}/>;
  else content=<CreateDeal onBack={()=>go('Explore')} onCreated={publish} busy={busy}/>;
  return <div className="app-shell"><header className="topbar"><button className="brand-button" onClick={()=>go('Home')}><Logo/></button><nav>{navItems.map(item=><button key={item} className={active===item?'active':''} onClick={()=>go(item)}>{item}</button>)}</nav><div className="top-actions"><div className="balance"><small>FAV</small><strong>{formatFav(fav)}</strong></div><button className="profile-button" onClick={()=>go('Profile')}>{initialsFor(session?.user?.user_metadata?.display_name || session?.user?.email)} <span>⌄</span></button></div></header><main>{content}</main>{selectedDeal&&<DealDetail deal={selectedDeal} fav={fav} favorites={favorites} onFavorite={toggleFavorite} onBack={()=>setSelectedDeal(null)} onBuy={buy} busy={busy}/>} {selectedOrder&&<OrderDetail order={selectedOrder} session={session} onBack={()=>setSelectedOrder(null)} onRelease={release} onRefund={refund} onStart={()=>sellerAction(startOrder)} onDeliver={()=>sellerAction(deliverOrder)} onChat={openChat} busy={busy} onReviewed={()=>notify('Review published.')}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
