import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import AppShell from './AppShell';
import { supabase } from './lib/supabase';
import { getMyUsernameStatus, completeUsername } from './lib/usernames';
import { getCurrentProfile } from './lib/profile';
jest.mock('./lib/supabase', () => ({ isSupabaseConfigured: true, supabase: { auth: {getSession: jest.fn(), onAuthStateChange: jest.fn()}, rpc: jest.fn() } }));
jest.mock('./lib/profile', () => ({ getCurrentProfile: jest.fn() }));
jest.mock('./lib/wallet', () => ({ getMyWallet: jest.fn() }));
jest.mock('./lib/usernames', () => ({ getMyUsernameStatus: jest.fn(), completeUsername: jest.fn(), suggestUsernames: () => ['available_name'] }));
jest.mock('./App', () => () => <div>Authenticated workspace</div>);
jest.mock('./components/AuthGate', () => () => <div>Sign in page</div>);
jest.mock('./components/ActivityCenter', () => () => null);
jest.mock('./components/AdminPanel', () => () => null);
jest.mock('./components/AdminOperations', () => () => null);
jest.mock('./components/AdminMessageReports', () => () => null);
jest.mock('./components/MiddlemanPanel', () => () => null);
jest.mock('./components/UsernameManager', () => () => null);
jest.mock('./components/DirectMessagingV2', () => () => null);
jest.mock('./components/DirectMessageBridge', () => () => null);
jest.mock('./components/MessageRequestListBridge', () => () => null);
jest.mock('./components/PrivateGroupBridge', () => () => null);
jest.mock('./components/CommunityFinishBridge', () => () => null);
jest.mock('./components/CommunityModeratorMessageBridge', () => () => null);
jest.mock('./components/SettingsLauncher', () => () => null);
jest.mock('./components/PublicProfileHost', () => () => null);
jest.mock('./components/FriendRequestCenter', () => () => null);
let listener;
const session = { user: { id:'member-a', email:'fixture@example.com', user_metadata: {display_name:'Fixture'} } };
beforeEach(() => {
  jest.clearAllMocks(); localStorage.clear();
  supabase.auth.getSession.mockResolvedValue({ data: {session} });
  supabase.auth.onAuthStateChange.mockImplementation(callback => {listener=callback;return {data:{subscription:{unsubscribe:jest.fn()}}};});
  supabase.rpc.mockResolvedValue({data:null});
  getCurrentProfile.mockResolvedValue({profile:{display_name:'Fixture'},wallet:{available_fav:'1'}});
  getMyUsernameStatus.mockResolvedValue({username:'generated_name',username_chosen:false});
});
test('generated usernames do not skip setup after reload or token refresh', async () => {
  localStorage.setItem('favourit_username:member-a','generated_name');
  render(<AppShell />);
  expect(await screen.findByRole('button',{name:'Claim my @ →'})).toBeInTheDocument();
  act(() => listener('TOKEN_REFRESHED',session));
  await waitFor(() => expect(supabase.auth.getSession).toHaveBeenCalled());
  expect(screen.queryByText('Authenticated workspace')).not.toBeInTheDocument();
  expect(supabase.rpc.mock.calls.some(([name]) => name.includes('claim'))).toBe(false);
});
test('a rejected username claim stays in setup; successful server confirmation proceeds', async () => {
  completeUsername.mockRejectedValueOnce(new Error('Username already taken')).mockResolvedValueOnce({username:'chosen_name'});
  render(<AppShell />);
  fireEvent.change(await screen.findByLabelText('Choose your username'),{target:{value:'chosen_name'}});
  fireEvent.click(screen.getByRole('button',{name:'Claim my @ →'}));
  expect(await screen.findByRole('alert')).toHaveTextContent('Username already taken');
  expect(screen.queryByText('Authenticated workspace')).not.toBeInTheDocument();
  getMyUsernameStatus.mockResolvedValue({username:'chosen_name',username_chosen:true});
  fireEvent.click(screen.getByRole('button',{name:'Claim my @ →'}));
  expect(await screen.findByText('Authenticated workspace')).toBeInTheDocument();
});
test('an unavailable setup status fails closed with a working retry', async () => {
  getMyUsernameStatus.mockRejectedValueOnce(new Error('Setup connection failed'));
  render(<AppShell />);
  expect(await screen.findByRole('alert')).toHaveTextContent('Setup connection failed');
  expect(screen.queryByText('Authenticated workspace')).not.toBeInTheDocument();
  getMyUsernameStatus.mockResolvedValue({username:'chosen',username_chosen:true});
  fireEvent.click(screen.getByRole('button',{name:'Retry account setup'}));
  expect(await screen.findByText('Authenticated workspace')).toBeInTheDocument();
});
