create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id) on delete cascade, target_type text not null check (target_type in ('deal','order','user','message','review')), target_id uuid not null, reason text not null, details text not null default '', status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')), resolved_by uuid references public.profiles(id) on delete set null, resolved_at timestamptz, created_at timestamptz not null default now()
);
create index if not exists reports_status_created_idx on public.reports(status,created_at desc);
create index if not exists reports_target_idx on public.reports(target_type,target_id);
alter table public.reports enable row level security;
drop policy if exists reports_insert_own on public.reports;
create policy reports_insert_own on public.reports for insert to authenticated with check (reporter_id=auth.uid());
drop policy if exists reports_select_own on public.reports;
create policy reports_select_own on public.reports for select to authenticated using (reporter_id=auth.uid() or exists(select 1 from public.moderators m where m.user_id=auth.uid() and m.role in ('moderator','admin')));
drop policy if exists reports_manage_moderators on public.reports;
create policy reports_manage_moderators on public.reports for update to authenticated using (exists(select 1 from public.moderators m where m.user_id=auth.uid() and m.role in ('moderator','admin'))) with check (exists(select 1 from public.moderators m where m.user_id=auth.uid() and m.role in ('moderator','admin')));
create or replace function public.create_report(p_target_type text,p_target_id uuid,p_reason text,p_details text default '') returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; v_user uuid:=auth.uid(); begin if v_user is null then raise exception 'not authenticated'; end if; if p_target_type not in ('deal','order','user','message','review') then raise exception 'invalid target'; end if; if nullif(trim(p_reason),'') is null or length(p_reason)>500 then raise exception 'invalid reason'; end if; if length(coalesce(p_details,''))>4000 then raise exception 'details too long'; end if; insert into public.reports(reporter_id,target_type,target_id,reason,details) values(v_user,p_target_type,p_target_id,trim(p_reason),trim(coalesce(p_details,''))) returning id into v_id; return v_id; end; $$;
revoke all on function public.create_report(text,uuid,text,text) from public,anon; grant execute on function public.create_report(text,uuid,text,text) to authenticated;
create or replace function public.resolve_report(p_report_id uuid,p_status text,p_note text default '') returns public.reports language plpgsql security definer set search_path=public as $$ declare v_report public.reports; v_user uuid:=auth.uid(); begin if not exists(select 1 from public.moderators where user_id=v_user and role in ('moderator','admin')) then raise exception 'not authorized'; end if; if p_status not in ('reviewing','resolved','dismissed') then raise exception 'invalid report status'; end if; update public.reports set status=p_status,resolved_by=case when p_status in ('resolved','dismissed') then v_user else resolved_by end,resolved_at=case when p_status in ('resolved','dismissed') then now() else null end,details=case when nullif(trim(p_note),'') is not null then left(details||E'\n'||trim(p_note),8000) else details end where id=p_report_id returning * into v_report; if not found then raise exception 'report not found'; end if; return v_report; end; $$;
revoke all on function public.resolve_report(uuid,text,text) from public,anon; grant execute on function public.resolve_report(uuid,text,text) to authenticated;
create or replace function public.notify_user(p_user_id uuid,p_type text,p_title text,p_body text,p_data jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin if p_user_id is null then return null; end if; insert into public.notifications(user_id,type,title,body,data) values(p_user_id,left(p_type,100),left(p_title,200),left(p_body,2000),coalesce(p_data,'{}'::jsonb)) returning id into v_id; return v_id; end; $$;
revoke all on function public.notify_user(uuid,text,text,text,jsonb) from public,anon,authenticated;
