-- Additive marketing intake only. No changes to profiles, orders, wallets or FAV.
-- Filename generated by `supabase migration new`; the Windows CLI could not write it.
create schema if not exists marketing_private;
revoke all on schema marketing_private from public, anon, authenticated;
grant usage on schema marketing_private to anon, authenticated;

create table marketing_private.programme (
  id boolean primary key default true check (id),
  applications_open boolean not null default false,
  founder_name text not null default 'Adam Levi',
  contact_email text not null default 'adamzoharlevi@gmail.com',
  updated_at timestamptz not null default now()
);
insert into marketing_private.programme(id) values(true);
alter table marketing_private.programme enable row level security;
revoke all on marketing_private.programme from public, anon, authenticated;

create table marketing_private.applications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text not null unique,
  name text not null,
  area text not null check (area in ('Visual design', 'Short-form video', 'Writing')),
  offer text not null,
  need text not null,
  portfolio text not null,
  availability text not null,
  pilot_consent boolean not null check (pilot_consent),
  contact_consent boolean not null check (contact_consent),
  adult_consent boolean not null check (adult_consent),
  digest_consent boolean not null default false,
  consent_version text not null,
  attribution jsonb not null default '{}'::jsonb,
  status text not null default 'applied' check (status in ('applied','interviewing','shortlisted','waitlisted','invited','declined','withdrawn')),
  notes text not null default ''
);
create index founding_applications_created_idx on marketing_private.applications(created_at desc);
alter table marketing_private.applications enable row level security;
revoke all on marketing_private.applications from public, anon, authenticated;

-- Definers live outside the Data API schema. Public wrappers are invokers.
-- The one anonymous write is deliberately an application intake, not an account mutation.
create function marketing_private.get_programme()
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('applications_open', applications_open, 'founder_name', founder_name,
    'contact_email', contact_email) from marketing_private.programme where id = true;
$$;
create function public.get_founding_programme()
returns jsonb language sql stable security invoker set search_path = '' as $$
  select marketing_private.get_programme();
$$;

create function marketing_private.accept_application(p_application jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_email text := lower(btrim(p_application->>'email'));
  v_key text;
  v_attribution jsonb := '{}'::jsonb;
  v_count integer;
begin
  if jsonb_typeof(p_application) is distinct from 'object' or octet_length(p_application::text) > 16000 then
    raise exception 'Invalid application.' using errcode = '22023';
  end if;
  if coalesce(p_application->>'website','') <> '' then
    raise exception 'Application could not be submitted.' using errcode = '22023';
  end if;
  if coalesce(v_email,'') !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' or length(v_email)>254 then
    raise exception 'Enter a valid email address.' using errcode = '22023';
  end if;
  if coalesce(length(btrim(p_application->>'name')),0) not between 1 and 100
    or coalesce(p_application->>'area','') not in ('Visual design','Short-form video','Writing')
    or coalesce(length(btrim(p_application->>'offer')),0) not between 20 and 1200
    or coalesce(length(btrim(p_application->>'need')),0) not between 20 and 1200
    or coalesce(length(btrim(p_application->>'availability')),0) not between 1 and 200
    or coalesce(length(p_application->>'portfolio'),0) not between 10 and 1000
    or coalesce(p_application->>'portfolio','') !~ '^https://[^[:space:]/@?#]+([/?#][^[:space:]]*)?$' then
    raise exception 'Check your name, service details, availability and HTTPS portfolio link.' using errcode = '22023';
  end if;
  if p_application->'pilot_consent' is distinct from 'true'::jsonb
    or p_application->'contact_consent' is distinct from 'true'::jsonb
    or p_application->'adult_consent' is distinct from 'true'::jsonb
    or p_application->>'consent_version' is distinct from 'founding-creators-2026-09-07' then
    raise exception 'Confirm the current pilot, contact and age conditions.' using errcode = '22023';
  end if;
  -- Serialise opening/closing and inserts, preventing concurrent quota overshoot.
  perform pg_advisory_xact_lock(7192026, 1);
  if not coalesce((select applications_open from marketing_private.programme where id = true), false) then
    raise exception 'Applications are not open yet. Nothing has been saved.' using errcode = '55000';
  end if;
  select count(*) into v_count from marketing_private.applications where created_at >= now() - interval '24 hours';
  if v_count >= 100 then raise exception 'Applications are busy. Please try again tomorrow.' using errcode = '54000'; end if;
  -- Do not store arbitrary browser history, full URLs, or caller-supplied identities.
  foreach v_key in array array['source','medium','campaign','referral'] loop
    v_attribution := v_attribution || jsonb_build_object(v_key,
      left(regexp_replace(coalesce(p_application->'attribution'->>v_key,''),'[^a-zA-Z0-9_.-]','','g'),80));
  end loop;
  insert into marketing_private.applications(email,name,area,offer,need,portfolio,availability,
    pilot_consent,contact_consent,adult_consent,digest_consent,consent_version,attribution)
  values(v_email,btrim(p_application->>'name'),p_application->>'area',btrim(p_application->>'offer'),
    btrim(p_application->>'need'),btrim(p_application->>'portfolio'),btrim(p_application->>'availability'),
    true,true,true,coalesce(p_application->'digest_consent' = 'true'::jsonb,false),p_application->>'consent_version',v_attribution)
  on conflict(email) do nothing;
  -- Same reply for duplicate email; never expose or overwrite an existing application.
  return jsonb_build_object('received',true);
end;
$$;
create function public.submit_founding_application(p_application jsonb)
returns jsonb language sql security invoker set search_path = '' as $$
  select marketing_private.accept_application(p_application);
$$;

create function marketing_private.admin_applications(p_status text default '')
returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if auth.uid() is null or not coalesce(public.is_favourit_admin(),false) then raise exception 'Admin access required.' using errcode='42501'; end if;
  return coalesce((select jsonb_agg(to_jsonb(a)) from
    (select * from marketing_private.applications where p_status='' or status=p_status order by created_at desc limit 500) a),'[]'::jsonb);
end;
$$;
create function public.admin_list_founding_applications(p_status text default '')
returns jsonb language sql stable security invoker set search_path = '' as $$
  select marketing_private.admin_applications(p_status);
$$;

create function marketing_private.update_application(p_id uuid, p_status text, p_notes text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not coalesce(public.is_favourit_admin(),false) then raise exception 'Admin access required.' using errcode='42501'; end if;
  if p_status not in ('applied','interviewing','shortlisted','waitlisted','invited','declined','withdrawn') or p_status is null
    or length(coalesce(p_notes,''))>3000 then raise exception 'Invalid status or notes.' using errcode='22023'; end if;
  update marketing_private.applications set status=p_status,notes=coalesce(p_notes,''),updated_at=now(),
    digest_consent = case when p_status='withdrawn' then false else digest_consent end
    where id=p_id;
  if not found then raise exception 'Application not found.' using errcode='P0002'; end if;
end;
$$;
create function public.admin_update_founding_application(p_id uuid,p_status text,p_notes text default '')
returns void language sql security invoker set search_path = '' as $$
  select marketing_private.update_application(p_id,p_status,p_notes);
$$;

create function marketing_private.set_programme_open(p_open boolean)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not coalesce(public.is_favourit_admin(),false) then raise exception 'Admin access required.' using errcode='42501'; end if;
  if p_open is null then raise exception 'Specify open or closed.' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(7192026, 1);
  update marketing_private.programme set applications_open=p_open,updated_at=now() where id=true;
end;
$$;
create function public.admin_set_founding_applications_open(p_open boolean)
returns void language sql security invoker set search_path = '' as $$
  select marketing_private.set_programme_open(p_open);
$$;

revoke all on all functions in schema marketing_private from public,anon,authenticated;
revoke all on function public.get_founding_programme() from public,anon,authenticated;
revoke all on function public.submit_founding_application(jsonb) from public,anon,authenticated;
revoke all on function public.admin_list_founding_applications(text) from public,anon,authenticated;
revoke all on function public.admin_update_founding_application(uuid,text,text) from public,anon,authenticated;
revoke all on function public.admin_set_founding_applications_open(boolean) from public,anon,authenticated;
grant execute on function marketing_private.get_programme(),marketing_private.accept_application(jsonb) to anon,authenticated;
grant execute on function public.get_founding_programme(),public.submit_founding_application(jsonb) to anon,authenticated;
grant execute on function marketing_private.admin_applications(text),marketing_private.update_application(uuid,text,text),marketing_private.set_programme_open(boolean) to authenticated;
grant execute on function public.admin_list_founding_applications(text),public.admin_update_founding_application(uuid,text,text),public.admin_set_founding_applications_open(boolean) to authenticated;
